### ISSUE TITLE
Live Scoreboard Problem

### ISSUE THREAD

**Issue by pavitra14** [Prophet731/BFAdminCP#102]
Gives this error whenever i try to see the Live Scoreboard of any server(Total 3 servers)
"Could not connect to server. It may be offline or port is closed. Please try again later."
I have entered the rcon pass and Battlelog guid(it may be wrong as i dont know from where to get it).
Please help!
Screenshot : http://prntscr.com/87i2fj

**Comment by Prophet731** [comment]
Please read this.

https://github.com/Prophet731/BFAdminCP/wiki/FAQ#5-error-connection-could-not-be-established-to-game-server

**Comment by pavitra14** [comment]
All ports in my web server are open!
still!

**Comment by pavitra14** [comment]
And also please tell me how you find my server GUID!

**Comment by sitekeeper** [comment]
Go to your server page in Battle log as in:
http://battlelog.battlefield.com/bf4/servers/show/PC/c1477ae6-7414-4d07-8790-ab9dff44adf5/AIR-MAPS-CONQUEST-TBGCLAN-COM-NO-LAG-SERVER-2/ 
 and the c1477ae6-7414-4d07-8790-ab9dff44adf5 is GUID

**Comment by pavitra14** [comment]
Ok, but how to fix that Live scoreboard problem?

**Comment by sitekeeper** [comment]
Your web host may have to allow remote access to your MySQL see if you have an option to do it in you control panel. In mine cPanel control panel it is listed as Remote Mysql (Remote Database Access Hosts) you need to add the game server and any procon/rcon ip's 

Hope this helps!
Bob

**Comment by pavitra14** [comment]
i have added the procon ip to it, i need to add the game server ip too?

**Comment by sitekeeper** [comment]
Yes hence the Rcon password in settings....

**Comment by Prophet731** [comment]
@pavitra14 

Your webserver needs to allow the game server rcon port on the outbound connection like it says in the FAQ. Otherwise, it won't work. Also you need to enter the rcon password for that server in the settings section.

**Comment by pavitra14** [comment]
I ll try it.

**Comment by pavitra14** [comment]
I added the game  server ip to mysql remote host from my cpanel as suggest by @sitekeeper
still no luck.

**Comment by pavitra14** [comment]
Fixed, Thanks for help
Had to contact the Hosting provider to get the port opened in firewall.

**Comment by pavitra14** [comment]
NOT FIXED, after opening the port in firewall, it is only working for bf3
It is not working for bf4.
Any idea?

**Comment by sitekeeper** [comment]
You have them open the ip;ports for all your servers?

**Comment by pavitra14** [comment]
i asked them to opened ports for all outbound connections

**Comment by pavitra14** [comment]
this is what they said
"port 47200 is currently opened in the firewall for both incoming and outgoing connections on Webhosting	384522"

**Comment by sitekeeper** [comment]
All of your servers all using same port? I know we use several including 47200, 47300 etc...

**Comment by pavitra14** [comment]
all of the servers are on different IP.
and i guess they have the same rcon port.
so should i ask the provider to unblock the port range 40000-50000 both tcp
and udp?

**Comment by sitekeeper** [comment]
it should say somewhere in your Game server control panel or welcome email from them the ports.

**Comment by Prophet731** [comment]
No, just give them the IP addresses of your servers and the rcon port needed. They will probably never open up a port range for you as that's a security risk.

**Comment by IamDontNoob** [comment]
Hello.
Live score board not work if i'm add new night map to Map rotation, Zavod:Graveayrd Shift
http://i.imgur.com/sIkUVDC.png
http://i.imgur.com/XBT4UmW.png
Can you help with this?

**Comment by Prophet731** [comment]
@IamDontNoob 

See http://www.adkgamers.com/topic/117610-bfacp-version-200/page-9#entry434102

**Comment by IamDontNoob** [comment]
@Prophet731 
Thank you.

**Comment by mikedevita** [comment]
hey there can you tell me specifically what tables its looking for, pretty sure ive got a case of bad data..

**Comment by CheckaWiemi** [comment]
I got the same problem with the livescoreboard on some BF3 servers and I've opened the Rconports for the server-IPs but it doesn't work on all servers. I don't know what to do
