### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by bjornthv** [Prophet731/BFAdminCP#104]
I'm getting a very nice error message on my server on trying to run BFadminCP: "Trying to get property of non-object (View: /home/admin/domains/tsbgamers.eu/public_html/acp/app/views/dashboard.blade.php)" 

I have no idea what it's trying to do or what I can do to fix it: http://acp.tsbgamers.eu/ As far as I know I have followed the setup guide and the server has all the prerequisites...

in case you need the server-info: http://www.acp.tsbgamers.com/info.php
I'm using the 2.0.0. version of BFadminCP.

**Comment by bjornthv** [comment]
laravel log: 

[2015-09-20 17:40:00] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/admin/domains/tsbgamers.eu/public_html/acp/app/storage/views/a1ba79c8b08a5a50a0f42ceef2ff88b6:87
Stack trace:
#0 /home/admin/domains/tsbgamers.eu/public_html/acp/app/storage/views/a1ba79c8b08a5a50a0f42ceef2ff88b6(87): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/admin/dom...', 87, Array)
#1 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/admin/dom...')
#2 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/admin/dom...', Array)
#3 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/admin/dom...', Array)
#4 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#5 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#6 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#7 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/dingo/api/src/Routing/Router.php(352): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#11 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/dingo/api/src/Routing/Router.php(205): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#18 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#19 /home/admin/domains/tsbgamers.eu/public_html/acp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#20 /home/admin/domains/tsbgamers.eu/public_html/acp/public/index.php(49): Illuminate\Foundation\Application->run()
#21 /home/admin/domains/tsbgamers.eu/public_html/acp/index.php(19): require_once('/home/admin/dom...')
#22 {main}

**Comment by Prophet731** [comment]
Run this query on the database 

```SQL
SELECT * FROM `tbl_playerdata` WHERE `GameID` = 0
```

If any results return delete those players.

**Comment by bjornthv** [comment]
MySQL Returned an empty result (0 rows). (Query took 0.0003 seconds).

**Comment by Prophet731** [comment]
Alright well I took a look at the link above and you are missing the required CSS and some JS files. You will need to upload those.
