### ISSUE TITLE
LiveScoreboard

### ISSUE THREAD

**Issue by ProudlyPoweredBy** [Prophet731/BFAdminCP#111]
Hello,

I have a problem when i'm logged in with the LiveScoreboard. Screenshot: http://prntscr.com/8ujg94

When i'm logged out, the LiveScoreboard is working fine.

**Comment by ProudlyPoweredBy** [comment]
Nevermind.

**Comment by ProudlyPoweredBy** [comment]
Another problem. I don't see any options for: http://prntscr.com/8uqsx4

On Livescoreboard, I can't take any actions on players or Chat. I can only View players, Chatlog and Roundstats.

**Comment by R3alflash** [comment]
In this Version the actions for players are not implemented. Some Updates will be come this week, maybe :)

For ur first problem:

Did u add a player id at a webadmin user? if not, do this and anything working fine.

PS: look there: http://www.adkgamers.com/topic/117610-bfacp-version-200/

**Comment by mambochambo** [comment]
i got the same problem. but its odd, its only happening for one server, and only in admin mode, in guest mode i can see the server- when i open console in browser and open the tab for the error it says:
{
"status": "error",
"message": "Fatal Error",
"execution_time": {
"time": 0.53,
"text": "Data crunched in 0.53 seconds"
},
"cached": false,
"data": [
"Unsupported operand types"
]
}

**Comment by mambochambo** [comment]
How do i enable the log entry? its not showing in the mangement section.

**Comment by Prophet731** [comment]
@mambochambo It should auto log to the logs folder in app/storage/logs

**Comment by mambochambo** [comment]
Thx!!
Next Issue ,/
Lifescoreboard is not showing Lifechat. I set UTC in my Database. And Adkats fetched the Timestamp, no errors so far. But when i type something in the chat, its not showing up...
I set feed data from Statslogger in Adkats and also manuall chat log.

**Comment by Prophet731** [comment]
hmmm... is the linux server time correct? Check if it's out of sync. That could be it too.

**Comment by mambochambo** [comment]
Ive set the Server timezone to the database time, its sysnced now.
but it didnt help.

**Comment by mambochambo** [comment]
Does anybody know how to make the livechat show the last message, for me its showing the first message, so i have to scroll down to the current messages... btw. sorry for posting so much
