### ISSUE TITLE
(WIP) Admin Actions doesnt take effect

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#115]
Hello Prophet,
it me again ,/ i managed to install the dev version, everything fine, but when i use the admin action for instance yelling a message, it does not take effect on the server
Can you please help me?
sincerely

**Comment by mambochambo** [comment]
how do i set the external controller api in adkats procon plugin, so i can use the webadmin tool

**Comment by Prophet731** [comment]
(WIP) = Work In Progress

1) I haven't pushed the code up yet to enable that and make it functional.

2) I'm not sure what you mean?

**Comment by mambochambo** [comment]
Ok, work in Progress. XD ill hope you finish soon
regards

**Comment by Prophet731** [comment]
@mambochambo I don't know if you follow the topic for this but it's been delayed.

http://www.adkgamers.com/topic/117610-bfacp-version-200/page-11#entry457799

**Comment by mambochambo** [comment]
Thx for the info- i installed it! its great-
but i got an error for one livescoreboard: end expects parameter 1 to be array, string given
can you help me fix that?

**Comment by mambochambo** [comment]
its also showing me this error on the population site
http://stats.gamers-community.net/api/v1/bf4/population
