### ISSUE TITLE
Live Scoreboard - Fatal Error

### ISSUE THREAD

**Issue by mox1972** [Prophet731/BFAdminCP#117]
Hello, sorry in advance if you have posted the solution as I am unable to find it.

Attached is a picture showing the communication issue. I have verified RCON password and ports are allowed.
![capture](https://cloud.githubusercontent.com/assets/15705139/11015813/2e33f650-853b-11e5-823f-40f04cd73bb2.PNG)

Thanks for any help!

Mox1972

**Comment by mambochambo** [comment]
i had the same Problem, and i reenabled the procon chat stats plugin, and reenabled adkats- after that the lifescoreboard was functioning

**Comment by Hary74656** [comment]
Had the same - found out it has to do with new maps, if i just give the server older maps it works

**Comment by Hary74656** [comment]
Hi again!
Just addet the new Maps to the following files and the Live Board works now:
File: /app/bfacp/ThirdParty/BF4/mapNames.xml

	<map uri="XP5_Night_01" name="Graveyard Shift" playmode="ConquestLarge0" />
	<map uri="XP6_CMP" name="Operation Outbreak" playmode="ConquestLarge0" />
(This is needet for all Modes, see examples in the File)

**Comment by mox1972** [comment]
Thanks for the response :) This did not fix the issue for me

**Comment by mox1972** [comment]
Thanks for the response. I just edited the mapNames.xml and added the maps; restarted both procon, adkats and the web server and still same issue :( wonder what else it could be?

**Comment by mox1972** [comment]
Thanks this worked !!

**Comment by Hary74656** [comment]
Allright :)

**Comment by Prophet731** [comment]
Sorry for the late reply, it never notified me about this ticket. Yeah, if you are running the new maps you will need to update the map and modes xml files. If either of you need help let me know, otherwise im going to close this ticket in 3 days.

**Comment by mox1972** [comment]
Hi prophet, thanks for getting back to me :)

All is working great, please close ticket
