### ISSUE TITLE
BFAdmin- Adding new Adkats User

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#120]
Hello Prophet,
sorry to bother you again- i have a Problem with adding Adkats User via BFAdmin, im using the 2.0r2 Version.
![image](https://cloud.githubusercontent.com/assets/15171835/11318293/ee13d59c-904b-11e5-8f89-602f34c285d9.png)
Can you help me fixing that. Is there something wrong with my Database?

**Comment by Prophet731** [comment]
Player ID of zero is invalid. That's why it's causing that error. Make sure each player has a unique id in the tbl_playerdata table.

**Comment by mambochambo** [comment]
i checked it. Each Player has his unique id. 
![image](https://cloud.githubusercontent.com/assets/15171835/11323586/939f716e-9115-11e5-8fb5-044539a18f56.png)
Is there anything else i can check?

**Comment by mambochambo** [comment]
Btw. i promised to donate- i do it next week- when i get fresh money.
Thx for your much help you offered me lately.

**Comment by Prophet731** [comment]
Alright no problem. Now as far as that error goes, I don't exactly remember what it's doing. The player id is either not being passed right or it's not fetching the player. I'll have to take a look maybe tomorrow or wednesday.

**Comment by mambochambo** [comment]
Hello Prophet- did you manage to take a look at it? sorry to bother you, but im not able to fix it myself ,(
