### ISSUE TITLE
REQUEST: All player ingame names

### ISSUE THREAD

**Issue by f0nt4** [Prophet731/BFAdminCP#122]
On the player page you have the chart which displays the ingame soldier names a player uses.
Only, it has a limitation because its not showing all of the names.
Therefor, it would be nice to have a button to display all of the ingame names used by a player.

Like this:
![preview](http://puu.sh/lWtSp/b7cd2950af.png)

**Comment by Prophet731** [comment]
Holy crap, that's a lot of name changes. I'll add a table below it as well as for the IP addresses.

**Comment by f0nt4** [comment]
Haha yes, he uses one for everyday. Don't know anyone else who changes his name that often.
Thanks for the effort in advance!
Also a little question, do you have in mind when the admin actions will start working? :)

**Comment by Prophet731** [comment]
http://www.adkgamers.com/topic/117610-bfacp-version-200/?p=465983
