### ISSUE TITLE
failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by f0nt4** [Prophet731/BFAdminCP#123]
When you try to edit an server. After clicking the server name on the admin/site/servers page:
![Screenshot](http://puu.sh/lWEWZ/fe75f83588.png)

**Comment by Prophet731** [comment]
Which version is this on?

**Comment by f0nt4** [comment]
I'm running the dev version with auto update by a cronjob :)

**Comment by Prophet731** [comment]
Oh yea, I forgot you were running it. Derp..

I've made some changes structurally so you it seems it has a conflict when it updated. Login to your server (ssh) and cd to the directory where it's installed. I would make a backup of the .env file in the root directory. After you made a copy of it run this command.

```
git reset --hard origin/develop
```

**Comment by f0nt4** [comment]
Did it and copied the env files back. But seems to be even more broken now? :(
http://puu.sh/lWH8r/dae0070779.png
As soon as I open the page.

**Comment by Prophet731** [comment]
delete the setup file located in app/bfacp/setup.php

**Comment by f0nt4** [comment]
AH, ofcourse, that worked.
But unfortunatly the edit server page is not yet fixed.
It shows me this: http://puu.sh/lWHBk/53423fe195.png

**Comment by Prophet731** [comment]
I'll take a look when I get home. I'm at work right now.

**Comment by f0nt4** [comment]
Great!

**Comment by Prophet731** [comment]
@f0nt4 Are you able to get on teamspeak?

**Comment by f0nt4** [comment]
Yeah, give me 5 minutes.
