### ISSUE TITLE
Live Scoreboard Fatal Error

### ISSUE THREAD

**Issue by static74** [Prophet731/BFAdminCP#124]
Hi Prophet,

First off, our group has always enjoyed your hard work and dedication to the community. 

We recently updated our bfadmincp to your latest 2.0 release and have the fatal error that was mentioned in the forums a few times. I did apply your map patch you posted below.
http://www.adkgamers.com/topic/117610-bfacp-version-200/page-9#entry434102

However, we still get the fatal error when trying to view live scoreboard. The Adkats plugin is up to date, as well as procon settings verified. All ports are opened to the subnet the procon server sits on. The database and admin cp are hosted on a different box.

Screen shot for reference. 
![capture](https://cloud.githubusercontent.com/assets/16431813/11998316/e2f72a84-aa67-11e5-938d-5cbd46989b46.PNG)

**Comment by Prophet731** [comment]
If you're running dragon valley you will need to update them again. If you're not, i'll need a link to your instance.

Update these files:

mapNames.xml
https://github.com/Prophet731/BFAdminCP/blob/develop/app/bfacp/ThirdParty/BF4/mapNames.xml

playModes.xml
https://github.com/Prophet731/BFAdminCP/blob/develop/app/bfacp/ThirdParty/BF4/playModes.xml

**Comment by static74** [comment]
Thank you that was the perfect fix. I really appreciate your time and help.

**Comment by Prophet731** [comment]
Those are for the admin actions which will be in version 2.0.1, which will be released on the 26th.

**Comment by windorose** [comment]
Hi Prophet 

I have same problem but on Hardline

**Comment by windorose** [comment]
i update mapNames.xml stil same problem

**Comment by Prophet731** [comment]
Did you update the gamemodes one as well if a new gamemode was introduced?

**Comment by windorose** [comment]
thank you for reply 
yes i do

**Comment by windorose** [comment]
Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists.
All my rcon port are open 
Can i limit log file coz the app generate more than 8 errors per second.

Your help will be appreciate.

Thank you

**Comment by Prophet731** [comment]
Put the app into maintenance mode (You can find the setting under the System Maintenance. Make sure to whitelist your IP in the .env file) then delete the log files that are there. After that open up the server page again then go back to the logs and get the logs.

**Comment by windorose** [comment]
ok

**Comment by windorose** [comment]
[2016-04-19 07:12:41] production.ERROR: exception 'ErrorException' with message 'simplexml_load_file(): /home/c1266022/BFACP/app/bfacp/ThirdParty/BFHL/mapNames.xml:99: parser error : StartTag: invalid element name' in /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php:401
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'simplexml_load_...', '/home/c1266022/...', 401, Array)
#1 /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php(401): simplexml_load_file('/home/c1266022/...')
#2 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(214): BFACP\Helpers\Battlefield->mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#3 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): Illuminate\Support\Facades\Facade::__callStatic('mapName', Array)
#4 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): BFACP\Facades\Battlefield::mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#5 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2527): BFACP\Battlefield\Server\Server->getCurrentMapAttribute(NULL)
#6 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2539): Illuminate\Database\Eloquent\Model->mutateAttribute('current_map', NULL)
#7 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2298): Illuminate\Database\Eloquent\Model->mutateAttributeForArray('current_map', NULL)
#8 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2257): Illuminate\Database\Eloquent\Model->attributesToArray()
#9 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Model->toArray()
#10 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2259): Illuminate\Database\Eloquent\Model->relationsToArray()
#11 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Database\Eloquent\Model->toArray()
#12 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(BFACP\Adkats\Record))
#13 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#14 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Support\Collection->toArray()
#15 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#16 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#17 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(735): Illuminate\Support\Collection->toArray()
#18 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(57): Illuminate\Support\Collection->toJson()
#19 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->morphToJson(Object(Illuminate\Support\Collection))
#20 /home/c1266022/BFACP/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\Support\Collection))
#21 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Support\Collection))
#22 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#23 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#24 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(231): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#28 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#30 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#31 /home/c1266022/BFACP/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#32 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#33 /home/c1266022/BFACP/public/index.php(49): Illuminate\Foundation\Application->run()
#34 {main} [] []
[2016-04-19 07:12:43] production.ERROR: exception 'ErrorException' with message 'simplexml_load_file(): /home/c1266022/BFACP/app/bfacp/ThirdParty/BFHL/mapNames.xml:99: parser error : StartTag: invalid element name' in /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php:401
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'simplexml_load_...', '/home/c1266022/...', 401, Array)
#1 /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php(401): simplexml_load_file('/home/c1266022/...')
#2 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(214): BFACP\Helpers\Battlefield->mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#3 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): Illuminate\Support\Facades\Facade::__callStatic('mapName', Array)
#4 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): BFACP\Facades\Battlefield::mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#5 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2527): BFACP\Battlefield\Server\Server->getCurrentMapAttribute(NULL)
#6 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2539): Illuminate\Database\Eloquent\Model->mutateAttribute('current_map', NULL)
#7 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2298): Illuminate\Database\Eloquent\Model->mutateAttributeForArray('current_map', NULL)
#8 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2257): Illuminate\Database\Eloquent\Model->attributesToArray()
#9 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Model->toArray()
#10 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2259): Illuminate\Database\Eloquent\Model->relationsToArray()
#11 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Database\Eloquent\Model->toArray()
#12 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(BFACP\Adkats\Record))
#13 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#14 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Support\Collection->toArray()
#15 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#16 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#17 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(735): Illuminate\Support\Collection->toArray()
#18 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(57): Illuminate\Support\Collection->toJson()
#19 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->morphToJson(Object(Illuminate\Support\Collection))
#20 /home/c1266022/BFACP/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\Support\Collection))
#21 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Support\Collection))
#22 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#23 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#24 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(231): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#28 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#30 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#31 /home/c1266022/BFACP/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#32 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#33 /home/c1266022/BFACP/public/index.php(49): Illuminate\Foundation\Application->run()
#34 {main} [] []
[2016-04-19 07:12:46] production.ERROR: exception 'ErrorException' with message 'simplexml_load_file(): /home/c1266022/BFACP/app/bfacp/ThirdParty/BFHL/mapNames.xml:99: parser error : StartTag: invalid element name' in /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php:401
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'simplexml_load_...', '/home/c1266022/...', 401, Array)
#1 /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php(401): simplexml_load_file('/home/c1266022/...')
#2 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(214): BFACP\Helpers\Battlefield->mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#3 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): Illuminate\Support\Facades\Facade::__callStatic('mapName', Array)
#4 /home/c1266022/BFACP/app/bfacp/Battlefield/Server/Server.php(193): BFACP\Facades\Battlefield::mapName('mp_bloodout', '/home/c1266022/...', 'TeamDeathMatch0')
#5 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2527): BFACP\Battlefield\Server\Server->getCurrentMapAttribute(NULL)
#6 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2539): Illuminate\Database\Eloquent\Model->mutateAttribute('current_map', NULL)
#7 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2298): Illuminate\Database\Eloquent\Model->mutateAttributeForArray('current_map', NULL)
#8 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2257): Illuminate\Database\Eloquent\Model->attributesToArray()
#9 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2346): Illuminate\Database\Eloquent\Model->toArray()
#10 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2259): Illuminate\Database\Eloquent\Model->relationsToArray()
#11 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Database\Eloquent\Model->toArray()
#12 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(BFACP\Adkats\Record))
#13 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#14 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(712): Illuminate\Support\Collection->toArray()
#15 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#16 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(714): array_map(Object(Closure), Array)
#17 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Support/Collection.php(735): Illuminate\Support\Collection->toArray()
#18 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(57): Illuminate\Support\Collection->toJson()
#19 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Http/Response.php(35): Illuminate\Http\Response->morphToJson(Object(Illuminate\Support\Collection))
#20 /home/c1266022/BFACP/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\Support\Collection))
#21 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Support\Collection))
#22 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#23 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\Support\Collection))
#24 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /home/c1266022/BFACP/vendor/dingo/api/src/Routing/Router.php(231): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#28 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#29 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#30 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#31 /home/c1266022/BFACP/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#32 /home/c1266022/BFACP/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#33 /home/c1266022/BFACP/public/index.php(49): Illuminate\Foundation\Application->run()
#34 {main} [] []

**Comment by windorose** [comment]
this is a log file

**Comment by Prophet731** [comment]
Ok so it's the same as the one you posted before. Can you zip up the files that you changed so I can see what's causing the problem.

**Comment by windorose** [comment]
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<playmodes>
    <playmode uri="TurfWarLarge0" name="Conquest Large"/>
    <playmode uri="TurfWarSmall0" name="Conquest Small"/>
    <playmode uri="Heist0" name="Heist"/>
    <playmode uri="Hotwire0" name="Hotwire"/>
    <playmode uri="BloodMoney0" name="Bloodmoney"/>
    <playmode uri="Hit0" name="Crosshair"/>
    <playmode uri="Hostage0" name="Rescue"/>
    <playmode uri="TeamDeathMatch0" name="Team Deathmatch"/>
    <playmode uri="CashGrab0" name="Bounty Hunter"/>
	<playmode uri="SquadHeist0" name="Squad Heist"/>
	<playmode uri="CaptureTheFlag0" name="Capture the Bag Maps"/>
</playmodes>`

**Comment by windorose** [comment]
[mapNames.txt](https://github.com/Prophet731/BFAdminCP/files/225405/mapNames.txt)

**Comment by Prophet731** [comment]
How did you setup this? Though the git command or downloaded the zip and uploaded it?

Upload this file. I removed a few things that weren't supposed to be there.

[mapNames.txt](https://github.com/Prophet731/BFAdminCP/files/225411/mapNames.txt)

**Comment by windorose** [comment]
[Battlefield.php.txt](https://github.com/Prophet731/BFAdminCP/files/225412/Battlefield.php.txt)
this battlefield.php found on helper folder

**Comment by windorose** [comment]
i installed via ZIP (uploaded)

**Comment by windorose** [comment]
now i have 2 error

**Comment by windorose** [comment]
[2016-04-19 07:30:32] production.ERROR: exception 'ErrorException' with message 'Illegal string offset 'full_name'' in /home/c1266022/BFACP/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php:396

**Comment by windorose** [comment]
[2016-04-19 07:15:49] production.ERROR: exception 'ErrorException' with message 'simplexml_load_file(): /home/c1266022/BFACP/app/bfacp/ThirdParty/BFHL/mapNames.xml:99: parser error : StartTag: invalid element name' in /home/c1266022/BFACP/app/bfacp/Helpers/Battlefield.php:401

**Comment by Prophet731** [comment]
Alright, download [this develop zip](https://github.com/Prophet731/BFAdminCP/archive/develop.zip) and upload the app folder, overwrite everything and see if you still get this problem. You don't need to upload [this file](https://github.com/Prophet731/BFAdminCP/blob/develop/app/bfacp/setup.php) however.

**Comment by windorose** [comment]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
HELP
Class 'Roumen\Feed\FeedServiceProvider' not found

**Comment by windorose** [comment]
need to reinstall
(can i install from the folder you sent me or i install V 2.0.1 ?)

**Comment by Prophet731** [comment]
I'm getting the necessary files for you. Give me a couple mins.

**Comment by windorose** [comment]
ok i'm waiting (thank you a lot for your help)

**Comment by Prophet731** [comment]
[vendor.zip](https://github.com/Prophet731/BFAdminCP/files/225460/vendor.zip)

Delete the vendor folder on your end then upload this vendor folder. This should correct that problem.

**Comment by windorose** [comment]
the ip i need to allow on.env.php is my internet IP or WEBHOsT ip?

**Comment by Prophet731** [comment]
It's yours.

**Comment by windorose** [comment]
:+1:

**Comment by windorose** [comment]
to reinstall i need to delete BFACP TBL on my DB?

**Comment by Prophet731** [comment]
You're not reinstalling. You're just updating the files.

**Comment by windorose** [comment]
i delete all folder

**Comment by windorose** [comment]
and delete subdomaine

**Comment by windorose** [comment]
in this case i need to delete bfacp tbl?

**Comment by Prophet731** [comment]
Why did you delete the subdomain? You didn't need to. All you had to do was re-upload folder/files and delete the setup file.

**Comment by windorose** [comment]
lol   I rushed to reinstall all

**Comment by windorose** [comment]
now it work 

THANK YOU A LOT for your time and your help.
