### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Jokerak** [Prophet731/BFAdminCP#125]
how to istall? 

.env.php  database server game? or hosting? 

ty

**Comment by Prophet731** [comment]
What method did you use to install it?

Are you able to join our teamspeak? It will go much faster with the help.

**Comment by Jokerak** [comment]
im upgrade all file in my website server .

2 .env.php im add database information Server game or webhosting

**Comment by Jokerak** [comment]
im italian sorry

**Comment by Jokerak** [comment]
Information in the database must include the server battlefield or site?

**Comment by Prophet731** [comment]
The database information that AdKats uses is what you must use for the DB.

**Comment by Jokerak** [comment]
please how to istalling? is autoistall?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2015-12-30 19:04 GMT+00:00 Prophet731 <notifications@github.com>:

**Comment by Prophet731** [comment]
It will autoinstall everything.

**Comment by Jokerak** [comment]
thanks works :)
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2015-12-30 22:07 GMT+00:00 Prophet731 <notifications@github.com>:
