### ISSUE TITLE
Illegal string offset in Live Scoreboard

### ISSUE THREAD

**Issue by sysLINK88** [Prophet731/BFAdminCP#130]
Thanks for your great tool.
According to our present update to the new version, we can no longer go to the points overview of Hardline Server. The survey for the BF4 servers goes.
I get on a BFH server error message:
production.ERROR: exception 'Exception Error' with message 'Illegal string offset' full_name '' in/var/www/clients/client1/web1/web/BFAdminCP/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php:396
on the Second:
production.ERROR: exception 'Exception Error' with message 'Undefined variable: default time' in /var/www/clients/client1/web1/web/BFAdminCP/app/bfacp/Helpers/Battlefield.php:371

The new cards I've added in the mapNames.xml

Thanks sysLINK

**Comment by Prophet731** [comment]
This is a known issue and I didn't see it when I was developing it. It will be fixed in the next update.

**Comment by sysLINK88** [comment]
Thanks for the info is there a way to change it myself?
Sodas there it runs would be reluctant now 2 BFadmin versions run on the server. If the develpp Branch, if necessary?

**Comment by Prophet731** [comment]
At the moment I have not wrote the fix for it yet so the develop branch wont work right now.

**Comment by sysLINK88** [comment]
Hi, so after a few attempts I got a workaround for Hardline.

BFAdminCP/app/bfacp/Repositories/Scoreboard/LiveServerRepository.php
@Line 504  exchange
            } elseif ($this->gameName == 'BFHL') {

		$this->TEAM1 = $teamFactions[0][6];
                $this->TEAM2 = $teamFactions[0][7];
		$this->TEAM3 = $teamFactions[0][6];
                $this->TEAM4 = $teamFactions[0][7];

then at the "lang" de-en-nl 
BFAdminCP/app/lang/de/scoreboard.php
add in factions
       6 => [
            'full_name' => 'Polizei',
            'short_name' => 'Cops',
        ],
        7 => [
            'full_name' => 'Kriminelle',
            'short_name' => 'Criminals',
        ],

**Comment by Prophet731** [comment]
I've updated my code with this fix. Thanks for figuring it out.

**Comment by sysLINK88** [comment]
Please note that when BF4 in SquadDeathmatch0 the error occurs even

**Comment by CheckaWiemi** [comment]
Got the same error with some of my BF3 servrs, but can't find the wrong code :-/

**Comment by mambochambo** [comment]
@sysLINK88 Thx for the Workaround, ive ammended the php files, and its working, i really appriciate it! DANKE

**Comment by Prophet731** [comment]
@mambochambo 

http://www.adkgamers.com/topic/136969-version-201/page-8?p=483550#entry483550

**Comment by mambochambo** [comment]
@sysLINK88 Hello syslink @Prophet731 
im running the master version, i get this Error on Squad Death Match Map, [2018-01-30 00:52:09] production.ERROR: exception 'ErrorException' with message 'Illegal string offset 'full_name'' in 
../app/bfacp/Repositories/Scoreboard/LiveServerRepository.php:404

im not familiar with php. can you help me out with a workaround like you did for BFH?

**Comment by Prophet731** [comment]
@mambochambo 

What game is this for? What is the gamemode your server is set to run? Also make sure this file exists and matches. There should be one for each language in the `lang` folder.

https://github.com/AdKats/BFACP/blob/master/app/lang/en/scoreboard.php

**Comment by mambochambo** [comment]
Thank you very much! i updated the scoreboard.php and now its working.
Im running bf4 server with squad death match
