### ISSUE TITLE
production.ERROR: exception 'Exception Error' scorboard

### ISSUE THREAD

**Issue by sysLINK88** [Prophet731/BFAdminCP#132]
production.ERROR: exception 'Exception Error' with message 'Undefined variable: default time' in /var/www/clients/client1/web1/web/BFAdminCP/app/bfacp/Helpers/Battlefield.php:371
To Fix :
BFAdminCP/app/bfacp/Helpers/Battlefield.php

276: case 'Bloodmoney0': -> case 'BloodMoney0':

361: case 'Bloodmoney0': -> case 'BloodMoney0':

**Comment by Prophet731** [comment]
If you can find me the latest battlefield hardline server docs i'll look though it and see what's missing and add it. I haven't been keeping up with hardline as we don't run it anymore so I haven't really bothered with it.

**Comment by sysLINK88** [comment]
Here you will find the latest documents for Server Admins
http://eaassets-a.akamaihd.net/dice-games/BFH/ServerDocumentation/BFH_PC_Server_R9_578901_AdministratorDocumentation.zip
Or do you mean something else?

**Comment by Prophet731** [comment]
Yes, that would be it.

**Comment by sysLINK88** [comment]
If you still want to have the latest ones of Hardline cards I can send you the well
