### ISSUE TITLE
error login default

### ISSUE THREAD

**Issue by Jokerak** [Prophet731/BFAdminCP#138]
Username: admin

Password: password

not work

**Comment by Prophet731** [comment]
If it doesn't create the default admin account then just create your account and then in the database in the table `bfacp_assigned_roles` change the `role_id` field from a 2 to a 1.

**Comment by Jokerak** [comment]
not registration http://praise-the-sun.it/bfadmincp/public/
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-07 1:52 GMT+00:00 Prophet731 <notifications@github.com>:

**Comment by Prophet731** [comment]
You cant run this application as a folder. It has to be on a subdomain with the subdomain document root pointing to the public folder.

**Comment by Jokerak** [comment]
ok
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-07 15:52 GMT+00:00 Prophet731 <notifications@github.com>:

**Comment by Jokerak** [comment]
im open subdomain  upload all file in bfadmincp folder
please help

http://bfadmincp.praise-the-sun.it/
http://bfadmincp.praise-the-sun.it/public/

how to Redirect  not work  no registration user
I do not know what to do if you want to step fpt access and hosting



2016-01-07 16:22 GMT+00:00 Cinema Streaming <bombolo76bg@gmail.com>:

**Comment by Jokerak** [comment]
subdomain you just created and create a directory called bfadmincp is
normal?

2016-01-08 0:25 GMT+00:00 Cinema Streaming <bombolo76bg@gmail.com>:

**Comment by Prophet731** [comment]
The subdomain MUST have its document root path set to the `public` folder. You should never have to access it in the browser.

**Comment by Prophet731** [comment]
Example: This was done in cPanel

This creates a subdomain of `acp.adkwebadmin.com` and its document root path is set to the `public` folder.

![Image of document root](https://i.gyazo.com/0c85e44a4d8b5c89524674540d2c7e13.png)

**Comment by Jokerak** [comment]
my root is /public_html/acp/public
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Questa
e-mail è stata inviata da un computer privo di virus protetto da Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2016-01-08 0:49 GMT+00:00 Prophet731 <notifications@github.com>:

**Comment by Jokerak** [comment]
I tried in every way and can not give you data hosting and fpt and you do it and also .htaccess files and broken send me email and I pay you and important

**Comment by Prophet731** [comment]
Send [me](http://www.adkgamers.com/user/1341-prophet/) a PM on our forums with the info and i'll get it working.

**Comment by Jokerak** [comment]
sended fpt in yuor forum access hosting
