### ISSUE TITLE
app/storage - directory permissions

### ISSUE THREAD

**Issue by TAM3105** [Prophet731/BFAdminCP#149]
Hello,

I've set (and checked) the permissions recursivly to 777 (V2.01) like all versions before and get this message:

"Directory "/www/htdocs/w0159e26/adkats.xyz.eu/app/storage" is not writable. Please change permissions to 0777"

Version 2.0.0 was ok. It's a new installation. Do you have any idea?

Thx
TAM

**Comment by Prophet731** [comment]
Also check in public/js/builds is set to 0777. There is a bug where it won't tell you the correct folder for some reason.

**Comment by TAM3105** [comment]
It works, thank you, but now I get this message:

"Error in exception handler."

Thx
TAM

**Comment by Prophet731** [comment]
Add your IP address to  the whitelist in the .env file. It will show a more detailed debug.

**Comment by TAM3105** [comment]
The reason was an error in "\vendor\laravel\framework\src\Illuminate\Container\container.php" in line 504. I had to administrate manually an user because there was no default user, but it works now.

Thx
TAM

**Comment by Prophet731** [comment]
So I can close this ticket?

**Comment by TAM3105** [comment]
Yes, thank you!!!
