### ISSUE TITLE
Live Chat (Web->Game messaging) not working

### ISSUE THREAD

**Issue by DeliciousJaffa** [Prophet731/BFAdminCP#15]
When attempting to send a message via the Live Chat interface on a server page, messages are not sent and show an "error" message like shown here: 
![10-11-96yinw-322x62](https://cloud.githubusercontent.com/assets/2257490/4602998/d19abb1e-5155-11e4-9465-c4fa145c0500.png)

**Comment by Prophet731** [comment]
Has this error continued or has it resolved itself?
