### ISSUE TITLE
Add Multiple Servers 

### ISSUE THREAD

**Issue by mated77** [Prophet731/BFAdminCP#166]
Hello. At first: great work ;-) Now my question: Is there a way to add more Servers to the Site without changing the DB / Adkats / Stats Logger to one DB for all Servers? We have 5 BF4 Servers and 6 BF3 Servers. If we now change all to one DB to show them on the site i think we lose all stats,bans.... for the Servers. Also if something went wrong with that DB we lose it for all Servers and not "only" for one. Is there a way or is it possible to add the option on the Page to say "Add Server #2 #3 ..." by setting there the other DB´(s) of the next Server(s)? @Prophet731

**Comment by Prophet731** [comment]
There will not be an option to add multiple databases for one installation. So you will need to have a install for each database if you only have 1 server per database. However, the system works better when everything is on a single database. If you want to migrate to a single database you will need to do some work to get that to work.

**Comment by mated77** [comment]
Ok, thank you for the reply...
