### ISSUE TITLE
error while trying to create a ban

### ISSUE THREAD

**Issue by Breakmaster90** [Prophet731/BFAdminCP#167]
I am getting the following error while trying to create a ban:
http://i.imgur.com/BAwRjNc.png

**Comment by Prophet731** [comment]
Click on the errorexception with the random number/letter file name. That's the screenshot need.

**Comment by Breakmaster90** [comment]
Here it is: http://i.imgur.com/tXxd3Hk.png

**Comment by Prophet731** [comment]
Did you set your soldiers under your account settings? If you didn't this may be the cause of your issue.

**Comment by Breakmaster90** [comment]
Sorry for the late response. The account was edited by mistake and yes it corrected the error.
Thank you

**Comment by Prophet731** [comment]
https://forum.myrcon.com/showthread.php?6045-Advanced-In-Game-Admin-and-Ban-Enforcer-AdKats-6-8-0-0/page138&p=131298#post131298
