### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by jamiehobson** [Prophet731/BFAdminCP#169]
trying to install bfadmincp getting this message tried bothe 2.0 and 2.01 versions and still the same message followed the readme but the message is the same everytime
Whoops, looks like something went wrong
i have tried this on 2 hosts but still the same issue 
.http://admin.sofadmin.co.uk/ 
not sure what  is rong hear maybe its a easy fix but i am no expert

**Comment by Prophet731** [comment]
When I went to it it's telling me the database connection settings are not configured. You need to set them in the .env.php file.

**Comment by mambochambo** [comment]
Did you set your Document root to public in your hosting settings? And did you set your site enabled in your apache2 sites available? you have to write a config file for admin.sofadmin.co.uk with the following content: http://www.adkgamers.com/topic/117923-installations-problems-with-admincp-2/
If its not working some reason could be, that you have to uncomment the rewrite root settings line in your .htacces file in your public folder. 
You can join our Teamspeak: gamers-community.net and ask for MAMBO, i can help you setting it up, i did it several times, Prophet helped me so often, now i became a little bit of an expert XD lol
