### ISSUE TITLE
Logfile for adminactions e.g. kill, kick, move etc

### ISSUE THREAD

**Issue by CheckaWiemi** [Prophet731/BFAdminCP#170]
Hi,

is there any possibility to add some functions for logging adminactions? It's just because we can then see which admin killed or kicked or moved which player and when.
Or is this still in BFAdminCP and I didn't see that?

Kind regards

**Comment by Prophet731** [comment]
Umm this is already there. It's just located under the admins player profile under records.

**Comment by CheckaWiemi** [comment]
Oh okay. But is there any way to see all adminactions on a special server? I got 6 servers in our BFAdminCP and sometimes I have to look on a specific server who made which action, so it's easier to see all adminactions on this server on one side, you know what I mean?

**Comment by Prophet731** [comment]
Yes, it's the same as this ticket #66.

**Comment by CheckaWiemi** [comment]
Ahhh thanks a lot :-)
