### ISSUE TITLE
Livescoreboard exception "BadMethodCallException"

### ISSUE THREAD

**Issue by Grift** [Prophet731/BFAdminCP#171]
Hi, im getting this every time i load up the livescoreboard. Chat, Admin actions and roundstats work fine. The rest are missing.
![capture](https://cloud.githubusercontent.com/assets/1593214/13251303/4aab6122-da6a-11e5-80d1-3f4de717422c.PNG)

**Comment by Prophet731** [comment]
In the .env.php file change these lines...


```PHP
'SESSION_DRIVER' => $session_driver,
'CACHE_DRIVER' => $cache_driver,
```

To this...

```PHP
'SESSION_DRIVER' => 'file',
'CACHE_DRIVER' => 'file',
```

**Comment by Grift** [comment]
Right not sure if it was a clean install or your suggestion but the problem is fixed now. However is it possible to set the time manually?
This is the actual time
![capture](https://cloud.githubusercontent.com/assets/1593214/13314288/52696b9a-dbdf-11e5-830b-905c6e0dac76.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1593214/13314289/55e4235a-dbdf-11e5-9245-25b3676abf5b.PNG)

This is what the CP is showing
![capture3](https://cloud.githubusercontent.com/assets/1593214/13314320/8c93f0c4-dbdf-11e5-820c-5c91c99aa424.PNG)
![capture4](https://cloud.githubusercontent.com/assets/1593214/13314323/8f2e307e-dbdf-11e5-9374-5cfd5d5e62fe.PNG)

**Comment by Prophet731** [comment]
In AdKats change the setting to have it post the chat logs manually. This should fix the problem.
