### ISSUE TITLE
Admin Actions

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#172]
Hello Prophet- i installed the new Version- everything is working fine so far, but i cant perma ban a Player, its not taking affect. Can you tell me what to do?
Best Regards

**Comment by Prophet731** [comment]
From the live scoreboard or from a players profile?

**Comment by mambochambo** [comment]
From the livescoreboard, i tick a Player, then hes marked, i take admin actions, perma ban player, klick ok, but it wont working. All  the other commands are working fine. only perma ban command doesnt work.

**Comment by mambochambo** [comment]
For that perma Ban- can i just copy the ban.php file from the 2.0 r2 Version to make it functionally again, or isnt that so easy? Is it not working in this version, or do only i have this Issue?
Sorry to bother you- 
Btw. All that requests and stuff like that from all that people- just wanna mention what great work you r doing. Thanks Prophet! This WebsiteCP is awesome, our Admins use it alot, and like it very much- if we could control the Mapssettings- like whats the next Map- then we even wouldnt use Procon anymore XD

**Comment by Prophet731** [comment]
No its not that simple. It's on the client side that's all but I haven't had time to work on it. Its only for the scoreboard part though, banning through the players profile will have the same effect, only difference between the two is that it removes them from the server in 1 request but I do believe AdKats will kick them out anyways if you banned them through their profile.

**Comment by mambochambo** [comment]
Take your time, its not that important..

**Comment by antivanity** [comment]
This function is important for my community. When can we expect a new version with bug fixes to come out ?

**Comment by Prophet731** [comment]
@antivanity 

I don't have a date yet. It's not stopping you from banning people though so it's not a "important" function shortcut. Which is what that is technically.
