### ISSUE TITLE
(off topic) Anticheatsearch Interface

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#174]
Hello Prophet- this is off topic. Do you know somebody who can program a tool- that checks a Player at  serveral Databases like Metaban, Fairfight, BF4db.com etc. at once. Or maybe a whole Platoon, like i enter to this site a Platoon ID, and every Player will be checked. Do you know somebody, who i can contact, who is capable of programming such a tool, or extension for your WebCP- Interface.
Its just an Idea, because i do a lot of Background checks lately.
Best Regards
Mambojumbo

**Comment by Prophet731** [comment]
Sorry for the late reply, been really busy. Problem with this is that some sites don't have an API that I can utilize effectively.
