### ISSUE TITLE
Livescoreboard Error

### ISSUE THREAD

**Issue by mated77** [Prophet731/BFAdminCP#177]
Hello Prophet.

Hope you can help me. We run the BFAdminCP and everything working fine .. since yesterday. 

Now we get the error on the Livescoreboard: Could not connect to server. It may be offline or port is closed. Please try again later.

All Ports are open, as before. We did not change anything. It just stop working. All other Data are OK and still visible. 

Thanks for your help.
Kind Regards mated
@Prophet731

**Comment by Prophet731** [comment]
Well that message is basicly saying either the server is offline or the firewall on your web server is not allowing the connection on the rcon port.

**Comment by mated77** [comment]
Thank you for the reply.
The firewall is open for it, the Servers are Online. Like i say: it was working like a charme before and then it stop working without a visible reason. Very mysterious…

**Comment by mated77** [comment]
Ah, now we got it. There was a error in the file for the firewall. The Hoster fixed the problem and everything is running now ;-)
