### ISSUE TITLE
error while generating new password

### ISSUE THREAD

**Issue by Breakmaster90** [Prophet731/BFAdminCP#178]
On v2.0.1 had the following error:
http://i.imgur.com/JWyFJWl.png

**Comment by Prophet731** [comment]
Sorry for the late reply. That error is telling me that the request to mailgun (for the email) didn't work. Could also be a firewall block on the outgoing connection but could also be just a temp issue.

**Comment by Breakmaster90** [comment]
since this is happening also with other accounts and the bfcp is hosted on a webhoster so checking the ports for me will be impossible. Is there any other ways to check it or change the ports ?

**Comment by Prophet731** [comment]
Is the email address valid? Can you take another screenshot of that exception but show the message that it shown at the top. It's cut off in the imgur link so I don't know what exactly the problem is. I was just taking a guess in my first reply.

**Comment by Breakmaster90** [comment]
Sorry for the late response!
http://i.imgur.com/0Cfn22L.png

**Comment by Prophet731** [comment]
Well, the problem is not the application at all, it's with your PHP configuration. You will need to ask your hosting provider to download a new clean copy of the cacert.pem file and update the path in the php.ini file.

http://stackoverflow.com/a/21114601

**Comment by Prophet731** [comment]
If this has been resolved i'm going to close the ticket.
