### ISSUE TITLE
Live Scoreboard Chat don't update

### ISSUE THREAD

**Issue by nortien** [Prophet731/BFAdminCP#183]
v.2.0.1
everything works fine, but the chat is not updated (realtime) in Live Scoreboard:
http://history.bashteam.ru/servers/live#!#id-1

the same server to another hosting (BFAdminCP v.2.0.0) works well and is updated chat:
http://history.xl-games.ru/servers/live#id-5

why? where to look and what to do?
thx

**Comment by Prophet731** [comment]
The chat is pulled from the database. Those two IDs are different. So that means you have your procon layer feeding the chat to the 2.0.0 version (database) vs the 2.0.1 version (database). Thats why. Did you clone it or anything?

**Comment by Prophet731** [comment]
Also check the procon settings to make sure it feeds the chat to the database.
