### ISSUE TITLE
Fatal Error 500

### ISSUE THREAD

**Issue by CheckaWiemi** [Prophet731/BFAdminCP#185]
Since today I got a big problem with my BFAdminCP 2.0.1
First of all there is no "mini-Livescoreboard"  on the startpage and if i go on Livescoreboard the following message appears: http://puu.sh/o854Q.png
Also if I wanna go on Webadmin -> servers there comes an error: http://abload.de/img/ooops86xbm.jpg

I don't know what to do, maybe someone can help me?

Kind regards

**Comment by CheckaWiemi** [comment]
Btw in the logfiles is this message: 
" Oops! Something went wrong.

A fatal error occured and application could not continue. Please report this incident to the site administrator and give them the following error message.
Allowed memory size of 100663296 bytes exhausted (tried to allocate 1448786144 bytes)"

**Comment by CheckaWiemi** [comment]
And after deleting a 1,36GB logfile just from today it says every second the following message in logfile: 
"production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /usr/www/users/jahbwa/BFAdminCP_BF4/app/bfacp/Battlefield/Server/Server.php:229"

**Comment by CheckaWiemi** [comment]
i guess it is just because 2 of our servers got a new IP, but how can I change it in BFAdminCP now? I can't enter the serversettings :-/

**Comment by Prophet731** [comment]
Sorry for the late response, been very busy. Are you still having trouble? The error that im guessing is that the server doesn't have an associated game id with it. Which would cause this problem.

**Comment by CheckaWiemi** [comment]
Hey,
no problem :-)
I found out that there was really a problem with the game-ID in the mySQL DB. I don't know why but there was always a 0 instead of a 1 in the DB. So I wrote a 1 in it and switched immediately to the AdminCP and it worked and I could deactivate the server.
But where does this 0 instead of 1 come from?

**Comment by Prophet731** [comment]
It's just a bug in the stats logger plugin, but if its fixed then im going close this ticket.

**Comment by CheckaWiemi** [comment]
That would be great. Thanks for it :-)
