### ISSUE TITLE
BFAdmin 2.0rc2

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#186]
Hello- i downgraded to Version rc2 because this Version was fully functional.
I tested it every time, i tried several different download links for this Version, but the Webinterface shows every time, that Version rc1 is installed. What am i doing wrong?
Thank you in Advance
Best Regards
http://prntscr.com/aqdq5i

**Comment by Prophet731** [comment]
Probably nothing, I just forgot to update that when I did an rc.2 release.

**Comment by mambochambo** [comment]
So, where or when can i download the rc.2 Release? I got it right, under the rc.2 download was the rc.1 release? sorry for bothering so much ,)

**Comment by Prophet731** [comment]
Sorry for the late response. 

This is the RC.2 Release.

https://sourceforge.net/projects/bfacp/files/v2.0.0-rc.2.zip/download

**Comment by mambochambo** [comment]
Thx for the reply- ive uploaded it- and did a composer install noscript-
but it still shows rc.1 release- have i done a wrong composer install?

**Comment by Prophet731** [comment]
No, that's the correct version. I said before I just forgot to update the version number in the application.

**Comment by mambochambo** [comment]
Sorry, its the right Version, somehow in the right down corner it says 2.0rc01 but its the rc2 version
Thank you for your help
