### ISSUE TITLE
Memberlist- Memberprofile

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#191]
Hello Prophet- 
i cant acces the Profile of the Memberlist- it says oops something went wrong, when i open console it says server responded with 500 error. For some Reason its only my Profile, everybodys else is working.
http://prntscr.com/awf8n0
Thank you in advance
Best Regards

**Comment by Prophet731** [comment]
Whitelist your IP address in the .env file and it should show more detailed debug information.

**Comment by mambochambo** [comment]
ok, ill try, its not that important, bec its only my profile ,)

**Comment by mambochambo** [comment]
in the rc2 version is no .env file ,/

**Comment by mambochambo** [comment]
#1 Undefined offset: 32 (View: /var/www/vhosts/gamers-community.net/bfadmin.gamers-community.net/app/views/public/user/profile.blade.php)
#2                                            <span class="time"><i class="fa fa-clock-o"></i> <?php echo date('g:i:s a', strtotime($e['record_time'])); ?></span>
                                            <h3 class="timeline-header"><?php echo $servers[$e['server_id']]; ?></h3>
                                            <div class="timeline-body">
undefined offset32

**Comment by Prophet731** [comment]
Honestly I don't know, I haven't touched it in over a year so i kinda forgot most of that code base.

**Comment by mambochambo** [comment]
ok, u can close this topic, its not that important, its some database issue i think...

**Comment by Prophet731** [comment]
Alright
