### ISSUE TITLE
Error login Can't create an account

### ISSUE THREAD

**Issue by windorose** [Prophet731/BFAdminCP#193]
Hi 

I cant connect with user :admin  PW : password

And i cant create a new account .

![bfa](https://cloud.githubusercontent.com/assets/18490426/15050104/c62b9fc8-12bf-11e6-805d-d7681e2c223a.png)

**Comment by windorose** [comment]
All tables are created on DB .

**Comment by windorose** [comment]
What i can do prophet?

**Comment by Prophet731** [comment]
Sorry for late reply, been busy with work.

Are the tables filled with the data or no? From your screenshot I see the create new account is missing from the login page. Make sure the permissions table (bfacp_permissions) is not empty. If it is let me know and can you access the shell command line or no?

**Comment by windorose** [comment]
Hi Prophet731

bfacp_permission is not empty .
I removed all bfacp_ tables and reupload setup.php and reinstall , still same problem

I have 2 webhost 
the first one where i have my DB (don,t have access to shell).
the second one (linked with DB located on 1st webhost)  i have access shell and i tried the cmd : php artisan db:seed i got Status: 500 Internal Server Error (when i m on BFACP root folder) and got Status: 404 Not Found when i was on vendor folder .

**Comment by Prophet731** [comment]
The only folder you need to access is the index.php file in the public folder. That's it.

What was the 500 error when you ran it on the command line?

**Comment by windorose** [comment]
yes when i run php artisan db:seed on SSH

**Comment by Prophet731** [comment]
Did you setup the .env file with the correct creds?

**Comment by windorose** [comment]
yes and i add my ip to whitelist

**Comment by Prophet731** [comment]
Run that command one more time, then go into the `app/storage/logs` folder and post back the log file. Please upload the file not copy and paste. You can attach it as a reply on github.

**Comment by windorose** [comment]
ok

**Comment by windorose** [comment]
need to delete bfacp_ tabele before run the cmd?

**Comment by Prophet731** [comment]
yea

**Comment by windorose** [comment]
[log-cgi-fcgi-2016-05-07.txt](https://github.com/Prophet731/BFAdminCP/files/253527/log-cgi-fcgi-2016-05-07.txt)

**Comment by Prophet731** [comment]
Ok run these commands in order. Tell me if that does anything.

`php artisan migrate`
`php artisan db:seed`

**Comment by windorose** [comment]
the same error for 2 cmd
Status: 500 Internal Server Erro

**Comment by Prophet731** [comment]
Give me the logs for that now.

**Comment by windorose** [comment]
[log-cgi-fcgi-2016-05-07.txt](https://github.com/Prophet731/BFAdminCP/files/253530/log-cgi-fcgi-2016-05-07.txt)

**Comment by Prophet731** [comment]
Hmm... The logs are telling me that the tables don't exist. Run this command and tell me what it says. It should say table migrations created or something like that.

`php artisan migrate:refresh`

**Comment by windorose** [comment]
Status: 500 Internal Server Error
Content-type: text/html

**Comment by Prophet731** [comment]
Are you doing this on the command line? I've never seen it do that before.

**Comment by windorose** [comment]
yes i use putty

**Comment by windorose** [comment]
stitclan@stitclan.net [~/public_html/BF]# php artisan migrate:refresh
Status: 500 Internal Server Error
Content-type: text/html

**Comment by Prophet731** [comment]
What returns with this.

`php -v`

**Comment by windorose** [comment]
LoL its PHP 5.2.17 i think this why it not work 

PHP 5.2.17 (cgi-fcgi) (built: Oct  2 2013 09:23:52)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.2.0, Copyright (c) 1998-2010 Zend Technologies
    with Zend Optimizer v3.3.9, Copyright (c) 1998-2009, by Zend Technologies

**Comment by Prophet731** [comment]
Yeah, you need 5.5 min.

**Comment by windorose** [comment]
i will migrate to branzone i think it better?!!!

**Comment by Prophet731** [comment]
I haven't used branzone web hosting before so I can't tell you if it's better.

**Comment by windorose** [comment]
which one can you advise me ?

**Comment by windorose** [comment]
sorry I made you waste time

**Comment by Prophet731** [comment]
If you're comfortable with setting up your own VPS I would go that route, but if you're not the only company I would reconmened is [Site5](https://www.site5.com/hosting/web/)

**Comment by windorose** [comment]
Thank you a lot bro.

**Comment by windorose** [comment]
Hi prophet731

Can you please add vendor folder.

**Comment by windorose** [comment]
Log file

[log-cgi-fcgi-2016-05-12.txt](https://github.com/Prophet731/BFAdminCP/files/261902/log-cgi-fcgi-2016-05-12.txt)

**Comment by Prophet731** [comment]
Alright this is a simple fix, in the .env.php file change these following lines to this.

```PHP
'SESSION_DRIVER' => 'file',
'CACHE_DRIVER' => 'file',
```
