### ISSUE TITLE
uploaded 2.0.2 errors

### ISSUE THREAD

**Issue by FuzzyThor** [Prophet731/BFAdminCP#194]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
HELP
Class 'Roumen\Feed\FeedServiceProvider' not found

1. Symfony\Component\Debug\Exception\FatalErrorException
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­ProviderRepository.php157
0. Illuminate\Exception\Handler handleShutdown
<#unknown>0

**Comment by Prophet731** [comment]
Delete the vendor folder and re-upload it.

**Comment by FuzzyThor** [comment]
Thanks! That did the trick.
