### ISSUE TITLE
Error 500  _soldiers.blade.php

### ISSUE THREAD

**Issue by windorose** [Prophet731/BFAdminCP#197]
Hi Prophet 
When i select some player on player list or BFAdmincp user or Adkats players i have this error : 

Trying to get property of non-object (View: /home/stitclan/BFA/app/views/partials/player/_soldiers.blade.php) (View: /home/stitclan/BFA/app/views/partials/player/_soldiers.blade.php)

**Comment by windorose** [comment]
[2016-05-15 08:26:00] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/stitclan/BFA/app/storage/views/e1d034b6765e35c768940cf2bfde9774:27 
Stack trace:
#0 /home/stitclan/BFA/app/storage/views/e1d034b6765e35c768940cf2bfde9774(27): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/stitclan/...', 27, Array)
#1 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/stitclan/...')
#2 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/stitclan/...', Array)
#3 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/stitclan/...', Array)
#4 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#5 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#6 /home/stitclan/BFA/app/storage/views/ebed0a4ca7ed3f0079f087c52d69cd30(54): Illuminate\View\View->render()
#7 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/stitclan/...')
#8 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/stitclan/...', Array)
#9 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/stitclan/...', Array)
#10 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#11 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#12 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#13 /home/stitclan/BFA/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#14 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#15 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#16 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#17 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#22 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 /home/stitclan/BFA/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 /home/stitclan/BFA/public/index.php(49): Illuminate\Foundation\Application->run()
#27 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /home/stitclan/BFA/app/views/partials/player/_soldiers.blade.php)' in /home/stitclan/BFA/app/storage/views/e1d034b6765e35c768940cf2bfde9774:27
Stack trace:
#0 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/stitclan/...', Array)
#2 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/stitclan/...', Array)
#3 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /home/stitclan/BFA/app/storage/views/ebed0a4ca7ed3f0079f087c52d69cd30(54): Illuminate\View\View->render()
#6 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(37): include('/home/stitclan/...')
#7 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/stitclan/...', Array)
#8 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/stitclan/...', Array)
#9 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#10 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#11 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#12 /home/stitclan/BFA/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#14 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#15 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#16 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /home/stitclan/BFA/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /home/stitclan/BFA/public/index.php(49): Illuminate\Foundation\Application->run()
#26 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /home/stitclan/BFA/app/views/partials/player/_soldiers.blade.php) (View: /home/stitclan/BFA/app/views/partials/player/_soldiers.blade.php)' in /home/stitclan/BFA/app/storage/views/e1d034b6765e35c768940cf2bfde9774:27
Stack trace:
#0 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/home/stitclan/...', Array)
#2 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/home/stitclan/...', Array)
#3 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /home/stitclan/BFA/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(381): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Dingo\Api\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /home/stitclan/BFA/vendor/dingo/api/src/Routing/Router.php(220): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#14 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#15 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /home/stitclan/BFA/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /home/stitclan/BFA/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []

**Comment by windorose** [comment]
[log-cgi-fcgi-2016-05-15.txt](https://github.com/Prophet731/BFAdminCP/files/264884/log-cgi-fcgi-2016-05-15.txt)

**Comment by Prophet731** [comment]
```SQL
DELETE FROM `tbl_playerdata` WHERE `GameID` = 0
```

Run that query on your database.

**Comment by windorose** [comment]
Thank you bro ?
it,s work now.

**Comment by windorose** [comment]
An other think Prophet 

I have 3 servers , on dashboard BFHL population 
2 servers are showed correctly but the third one is always showed 0/10 player
and when i check on live scoreboard it show the server correctly.

**Comment by Prophet731** [comment]
Make sure xpkillers stats logger plugin for that server is running correctly. That information is pulled from the database.

**Comment by windorose** [comment]
yes it's.
