### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by f0nt4** [Prophet731/BFAdminCP#200]
Hey Prophet,

Seems like there are some misses in the permissions system.
If I enable chatlogs to be visible for public, I get the menu option as guest, but clicking it gives a forbidden error.
The banlist is always visible on the dashboard, and the reason is always visible on the player's profile.
Could you make a permission so the banlist is also like the chatlog an option to be available for guests?

Grtz Fonta

**Comment by Prophet731** [comment]
Well then they can still see it in the players records if I just did those two things you mentioned. If you don't want anyone to view them just make the site for registered users only.

**Comment by f0nt4** [comment]
You're right, it's not just the 2 things I mentioned. 
I don't really care that the bans are visible for the public, but I just stumbled across it while I was viewing the site being logged out.
Thought it would be good to mention this because at the moment, imho it isn't really working as it's supposed to.
Like making the chat history public, but when you click it, it says forbidden xD
View the banlist is already an setting for the roles, it doesn't have any use at the moment?

**Comment by Prophet731** [comment]
The permission "view the banlist" is for the banlist link itself and the view for it. The latest bans feed on the dashboard are not part of that permission set for a reason. As for the chat history being public it shouldn't be if you set view chatlogs to disabled. The link should never show up for guests.
