### ISSUE TITLE
Request: Idle timeout sound enable/disable option

### ISSUE THREAD

**Issue by f0nt4** [Prophet731/BFAdminCP#201]
Hi Prophet,

A small and unimportant request.
Could you make an option to enable/disable the idle timeout sound?
Would be awesome!

Kind regards,

Fonta

**Comment by Prophet731** [comment]
Do you leave the scoreboard idle for 30 mins a lot? The sound is just to let you know that it will be disabled if you don't do *something* on the page. It should also only play for the last 10 seconds I believe on the countdown.

**Comment by f0nt4** [comment]
Yes I keep it open idle a lot on some tab of my browser or in the background when I'm playing myself.
I know what it's for, but it doesn't have to warn me with a sound. I would really appreciate an option to disable it. 
An option because I can image that some people do find it helpful.

**Comment by Prophet731** [comment]
I just realized it was set to countdown from 20 and not 10. I've thought about it more and I decided im just going to disable it for everyone for now.

**Comment by f0nt4** [comment]
Haha, disabling it for everyone is also an option ofcourse :p 

Btw, since you worked on the geodb searching for players and the playerslist isn't working anymore: See http://bfadmin.bug-community.com/players

**Comment by Prophet731** [comment]
Ahh you're running 2.1. You will need to do a composer update from the command line.

**Comment by f0nt4** [comment]
Ah greet. That fixed it!

**Comment by Prophet731** [comment]
I'm pushing up the change now, so you can run git pull to fetch it. But I assume it's doing git pull on a cron job so you shouldn't need to do it.
