### ISSUE TITLE
Error Trying to get property of non-object 

### ISSUE THREAD

**Issue by windorose** [Prophet731/BFAdminCP#203]
Hi Prophet731

Everything was working fine until yesterday, i found 800Mb of log folder.

and now i cant see my 3 servers on Dashboard and when i check on servers setting i have a lot of error like this : 

ErrorException (E_ERROR)

Trying to get property of non-object (View: /home/stitclan/BFA/app/views/admin/site/servers/index.blade.php)
Open: /home/stitclan/BFA/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php

    // an exception is thrown. This prevents any partial views from leaking.
    try
    {
    include $__path;
    }
    catch (\Exception $e)
    {
    $this->handleViewException($e, $obLevel);
    }

I delete all log files to generate a new one 
here is : 
[log-cgi-fcgi-2016-05-21.txt](https://github.com/Prophet731/BFAdminCP/files/275664/log-cgi-fcgi-2016-05-21.txt)

**Comment by windorose** [comment]
now it work. I did not modify anything

**Comment by windorose** [comment]
[2016-05-21 09:40:54] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/stitclan/BFA/app/storage/views/e5ce73c89cf0d1449f7ad6a0ec6afb15:131

[log-cgi-fcgi-2016-05-21.txt](https://github.com/Prophet731/BFAdminCP/files/275808/log-cgi-fcgi-2016-05-21.txt)

**Comment by Prophet731** [comment]
What page is that happening on?

**Comment by windorose** [comment]
When i click on some player not with all (dashboard)

**Comment by Prophet731** [comment]
```SQL
SELECT * FROM tbl_playerdata WHERE GameID = 0
```

Do any results return with that query, nothing should return with that.

**Comment by windorose** [comment]
0 - 29 (243 total, Query took 0.0015 sec) [PlayerID: 6794 - 6753]

**Comment by Prophet731** [comment]
```SQL
DELETE FROM tbl_playerdata WHERE GameID = 0;
```
Run that then restart your procon layers

**Comment by windorose** [comment]
That's why i seen a different count of unique player (between DB & dashboard) and why it's happned?
Fixed thank you for help.
