### ISSUE TITLE
Procon Event Display

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#204]
Hello Prophet- can you somehow implement the Procon Events, for instance i can see if someone is only killing with Headshots? It would be a great Feature. 2nd. is there a possibility to implement the Option to choose the next Map or to edit Mapcicle. If this would be integrated into the Controlpanel, i woudnt have to use procon anymore ,)
Best Regards

**Comment by Prophet731** [comment]
1) Currently not possible with just PHP and the lag from ProCon events over the web wouldn't be worth it on the implementation.
2) I'll look into adding maplist editor, no promises though.
