### ISSUE TITLE
fresh install error

### ISSUE THREAD

**Issue by ChaT0n** [Prophet731/BFAdminCP#205]
Had this error on a new fresh install (v 2.0.2 from sourceforge), just at first lunch. After refreshing the page, nothing showed up.
http://imgur.com/zmB85bD

Also the tables were created and filled except for the default user

**Comment by Prophet731** [comment]
If the default user wasn't created just have them create an account and change their role id in the bfacp_assigned_roles table for that user from "2" to "1"

**Comment by ChaT0n** [comment]
I wasn't refeering to the default user but to the error on the install while starting the bfacp for the first time (linked in the picture)
Sorry my mistake in my post, i should have been more specific in my sentence

**Comment by Prophet731** [comment]
That error usually happens on the install script and I don't know why. But if it created the tables and populated the critical tables at least then you should be fine, just will have to do a few extra steps as I said above.

**Comment by killengage** [comment]
I had that error before. Running `composer update` in your bfacp root dir fixed it for me.

**Comment by ChaT0n** [comment]
will give it a try during next week

**Comment by ozersk** [comment]
I also can not install, the tables are not created. Please, help.
[http://prntscr.com/bf4e2b](url)

**Comment by Prophet731** [comment]
@ozersk You didn't follow the directions. Please go back and read the [readme](https://github.com/Prophet731/BFAdminCP/blob/master/README.md).

> This application was designed to run on a subdomain and not from a folder from the TLD. Make sure to create a subdomain and if possible have domain point to the public folder that's located under the root folder.

After you done that make sure the setup file is still located in app/bfacp/setup.php if it's not reupload that file before you visit the application page again.

**Comment by ozersk** [comment]
Do I understand you, BFAdminCP must lie at the root of the finished site? I have tried for many solutions, but no success. Can you help me with the installation or suggest? Please write me an email ozerskaristo@gmail.com
I am not in debt remain.

**Comment by ozersk** [comment]
@Prophet731 Do I understand you, BFAdminCP must lie at the root of the finished site? I have tried for many solutions, but no success. Can you help me with the installation or suggest? Please write me an email ozerskaristo@gmail.com
I am not in debt remain.

**Comment by killengage** [comment]
All folders within BFAdminCP must be at the root of your domain. Your domain should point to the /public folder.

**Comment by Prophet731** [comment]
1) Upload the bfacp to your web server
2) create a subdomain (name it whatever you want) and point its document root to the public folder located in the bfacp.

**Comment by ozersk** [comment]
It looks like the problem is that I have a different port Mysql 3307

**Comment by Prophet731** [comment]
https://github.com/Prophet731/BFAdminCP/blob/master/app/config/database.php#L47

In that file on your side add the port entry as shown below.

```PHP
'mysql' => [
            'driver'    => 'mysql',
            'host'      => getenv('DB_HOST') ?: 'localhost',
            'database'  => getenv('DB_NAME') ?: '',
            'username'  => getenv('DB_USER') ?: '',
            'password'  => getenv('DB_PASS') ?: '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'port' => 3307,
        ],
```

**Comment by Prophet731** [comment]
@ChaT0n 

Have you resolved this problem?

**Comment by ChaT0n** [comment]
Was overwhelmed with work.I will give it a try on friday and tell you if the solution of killengage works.

**Comment by ChaT0n** [comment]
tried again, using v 2.0.3 but still getting that error (see first post)
tables are created and feeded except again for the default admin (but that ain't a problem)

**Comment by killengage** [comment]
You executed `composer update` right ?

**Comment by ChaT0n** [comment]
yap, but still got this error.

@Prophet731 
I've noticed another bug, if I search for a player containing hexadecimal characters the search won't work: for example seacrh for a player abc12206, or abd, or 12354 won't give any positive results even if the players exist in the db.

**Comment by killengage** [comment]
Ok jammer.

Gr, Maurice

Verstuurd vanaf mijn iPad

**Comment by Prophet731** [comment]
That might be because when I wrote the function only certain characters where allowed to match what EA has for their name requirements. However only letters, numbers, underscore, and dash are allowed for a playername.

**Comment by ChaT0n** [comment]
can you release a fix for this when you can ?
Thanks

**Comment by Prophet731** [comment]
I'm curious as to why you have hexadecimal characters for names? Can you show me the entries from the DB side. What you provided here would work just fine.

**Comment by ChaT0n** [comment]
here is a small example https://youtu.be/QhJZF4GlyP4
As you can see the player abc10... exists but the search engine won't find him. And it is the same for all the players that contains only hexadecimal characters (A to F and 0 to 0)

**Comment by Prophet731** [comment]
> here is a small example https://youtu.be/QhJZF4GlyP4
> As you can see the player abc10... exists but the search engine won't find him. And it is the same for all the players that contains only hexadecimal characters (A to F and 0 to 0)

Do a git pull and tell me if this fixed the problem, or modify this file with my change.

https://github.com/Prophet731/BFAdminCP/commit/cc2c2694b9dbf0b9a8a2ae59c2b17712f053fe99

**Comment by ChaT0n** [comment]
It seems to be working. Thanks a lot

**Comment by Prophet731** [comment]
Ok.
