### ISSUE TITLE
Live Scoreboard

### ISSUE THREAD

**Issue by jaggedsoft** [Prophet731/BFAdminCP#206]
Hi there, I absolutely love AdKats and BFAdminCP!
We got everything installed, it appears to be working correctly, however once we go to the Live Scoreboard page, it doesn't list any of our servers.

![scoreb](https://cloud.githubusercontent.com/assets/4283360/15636291/adc38624-25ae-11e6-969e-fadf947ebdda.png)

Also, Chat logs just redirects us to the front page of the dashboard.
Thank you for putting so much effort into making A Different Kind of admin interface! :+1: 

Another request would be adding a button linking to 247fairplay.com from the player info page.

**Comment by jaggedsoft** [comment]
Possibly related is that its showing 0/0 players online

![23432capture](https://cloud.githubusercontent.com/assets/4283360/15636316/76f02cbe-25af-11e6-86ae-ee98c4a3fd3b.PNG)

**Comment by Prophet731** [comment]
Make sure your servers have a valid game id as well are enabled in the server management.

**Comment by jaggedsoft** [comment]
The ServerID is set to 1, is that what you're referring to? Also, what server management are you talking about? Thanks for your help! Awesome work.

**Comment by Prophet731** [comment]
No, the game id, it's a column. As for the server management it should be like this.

![a](https://i.gyazo.com/ef2666589f59e176bd54c9fa71faa158.png)

**Comment by jaggedsoft** [comment]
That's what I seem to be missing. The default login doesn't appear to be working, so I guess I am running as a regular user. Also, the support page linked from Github points to http://www.adkgamers.com/forum/265-adk-web-dev-support/ which is a broken link. Any way I can set my account as admin?
Thanks for the help and the support. You guys are great. I will send a donation as soon as I can afford it!

**Comment by Prophet731** [comment]
That link works but I think the permissions for guest aren't allowed. I'll have to talk to my community leader to fix that.

So you created a account correct? If so then go into the database and under the table bfacp_assigned_roles find your user id then change the role id for that entry from a 2 to a 1

**Comment by jaggedsoft** [comment]
It worked. Thank you so much! this is such an awesome tool. :+1:
