### ISSUE TITLE
The logs spam error occurs

### ISSUE THREAD

**Issue by ozersk** [Prophet731/BFAdminCP#209]
Tell me what to do?
![71ef595d895045f09750587fc7056886](https://cloud.githubusercontent.com/assets/19875789/15993694/75e10e8e-3107-11e6-84f2-77511d9520b0.png)

[http://image.prntscr.com/image/71ef595d895045f09750587fc7056886.png](url)

`Stack trace:
#0 C:\OpenServer\domains\BFAdminCP\app\bfacp\Repositories\Scoreboard\LiveServerRepository.php(515): Illuminate\Exception\Handler->handleError(8, 'Undefined offse...', 'C:\\OpenServer\\d...', 515, Array)
#1 C:\OpenServer\domains\BFAdminCP\app\bfacp\Repositories\Scoreboard\LiveServerRepository.php(389): BFACP\Repositories\Scoreboard\LiveServerRepository->setFactions()
#2 C:\OpenServer\domains\BFAdminCP\app\bfacp\Repositories\Scoreboard\LiveServerRepository.php(220): BFACP\Repositories\Scoreboard\LiveServerRepository->serverinfo()
#3 C:\OpenServer\domains\BFAdminCP\app\bfacp\Http\Controllers\Api\ServersController.php(103): BFACP\Repositories\Scoreboard\LiveServerRepository->attempt()
#4 [internal function]: BFACP\Http\Controllers\Api\ServersController->scoreboard('1')
#5 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#6 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('scoreboard', Array)
#7 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(BFACP\Http\Controllers\Api\ServersController), Object(Dingo\Api\Routing\Route), 'scoreboard')
#8 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Dingo\Api\Routing\Route), Object(Illuminate\Http\Request), 'BFACP\\Http\\Cont...', 'scoreboard')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1')
#10 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#11 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 C:\OpenServer\domains\BFAdminCP\vendor\dingo\api\src\Routing\Router.php(231): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Dingo\Api\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\OpenServer\domains\BFAdminCP\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\OpenServer\domains\BFAdminCP\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 C:\OpenServer\domains\BFAdminCP\public\index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []`

**Comment by Prophet731** [comment]
Have you uploaded all the files? That error is telling me it doesn't find a required value it was expecting. Make sure the file in `app/lang/(langcode)/scoreboard.php has the entries from the base file https://github.com/Prophet731/BFAdminCP/blob/master/app/lang/en/scoreboard.php

**Comment by ozersk** [comment]
Compared lacked team names BFH.
thanks for help
