### ISSUE TITLE
Two database 

### ISSUE THREAD

**Issue by windorose** [Prophet731/BFAdminCP#210]
Hi prophet731

It's possible to use 2 different database?
I have 4 Servers now all are one database but i got some trouble with XpKiller's Procon Chat, GUID
i want put one server on other DB (on other web host).

Thank you

**Comment by Prophet731** [comment]
No. It was designed to only run on a single database. If you want to run the BFACP with another database you would have to install the application again.

**Comment by windorose** [comment]
Ok thank you for reply.

**Comment by windorose** [comment]
it possible to show on player info how much time and rounds he played on servers ?

**Comment by Prophet731** [comment]
Which version are you running? It should already be shown

![](https://i.gyazo.com/a480bcbdb3199ad8149b239bb223992a.png)

**Comment by windorose** [comment]
Sorry my bad (i dont speak english very well)
I mean sort the all player on  Player Listing by time played or rounds played or reputation?

**Comment by Prophet731** [comment]
It's possible, but that might cause huge lag in the display of the results. I would need to look into that.

**Comment by windorose** [comment]
ok thank man
