### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by N1l5** [Prophet731/BFAdminCP#216]
Hi Prophet,

I installed bfadmincp on my webspace a few days ago, but I couldnt log in because the default admin login was wrong.
I deleted all files and deleted the SQL tables manually. After the reinstall I now get the error message:

"Database Error! Sorry, something went wrong with the database."

I think I did something wrong with the manual table deleting. I am pretty sure the SQL informations to my database are correct. I cant explain to me, what to do to fix that.

Any ideas? Thanks for your work

**Comment by killengage** [comment]
You only deleted the bfacp tables i hope ?

**Comment by N1l5** [comment]
Yes I did, didnt touch anything from adkats or something else

**Comment by Prophet731** [comment]
Which version are you trying to run?

**Comment by N1l5** [comment]
I try to run version 2.0.2.

**Comment by Prophet731** [comment]
Did you reupload the application or just delete the tables in the database? If it's the latter then you need to re-upload the file in app/bfacp/setup.php to your webspace and refresh the application.

**Comment by N1l5** [comment]
Great, now it´s working. Thank you!
But I still can´t login with the default admin account. (Incorrect username, email or password.)
I read a thread somewhere how to fix that in the database. But sadly I can´t find it anymore.
Do you got a idea again?

**Comment by Prophet731** [comment]
Just create your account and once created go into the assigned users role table and change your role id from 2 to 1

**Comment by N1l5** [comment]
Nice, it´s working now.
I still got the cURL error 60, but that is hoster related I guess.
Thanks for your help.

**Comment by Prophet731** [comment]
yes the curl error 60 is a hoster issue that can be resolved easily.
