### ISSUE TITLE
When tempbanning a player from a report i get "Undefined index: setting_name"

### ISSUE THREAD

**Issue by killengage** [Prophet731/BFAdminCP#217]
I tried to tempban a player from a report with 7200 minutes (6 days). When pressing ok i got this message above the envelope "Undefined index: setting_name"

**Comment by killengage** [comment]
No problem :) Lets make this app great :)
I'm on v2.1 , i can use this file ?

**Comment by Prophet731** [comment]
What returns for this?

```SQL
SELECT * FROM adkats_settings WHERE setting_name = 'Maximum Temp-Ban Duration Minutes'
```

**Comment by killengage** [comment]
ServerID                            Setting_name       Setting_type    Setting_value

        1      Maximum Temp-Ban Duration Minutes 	double 	5256000
 	2 	Maximum Temp-Ban Duration Minutes 	double 	5256000
	3 	Maximum Temp-Ban Duration Minutes 	double 	5256000

**Comment by Prophet731** [comment]
Ok, and does the server you're trying to issue that report action on in that list above? If not, then that's your problem.

**Comment by killengage** [comment]
They are in the list. Just did a tempban (2 min.) test on reports on all 3 servers, still get the same message.

**Comment by Prophet731** [comment]
In app/Http/Controllers/Api/ReportsController.php on line 95, change the world `pluck` with `lists`. Then see if it works.

**Comment by killengage** [comment]
Unfortunately the same error. If needed for debugging i can give you ssh and mysql webaccess. I only need your ip address since i block these services.

**Comment by Prophet731** [comment]
Can you delete your logs from `storage/logs` then run that command again afterwards. Then post back the log file. Attach the file, don't post the contents in the text box.

**Comment by killengage** [comment]
Here it is. I changed back the ReportsController.php to `pluck`

[laravel-2016-07-05.txt](https://github.com/Prophet731/BFAdminCP/files/347440/laravel-2016-07-05.txt)

**Comment by Prophet731** [comment]
Do a git pull and tell me if it fixes it?

**Comment by killengage** [comment]
Sorry mate, next one:

Argument 1 passed to BFACP\Helpers\Main::getAdminPlayer() must be an instance of BFACP\Account\User, null given, called in /var/www/vhosts/four-eleven.eu/bacp.four-eleven.eu/BFAdminCP/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 219 and defined

**Comment by Prophet731** [comment]
Ok now try

**Comment by killengage** [comment]
#
[laravel-2016-07-05.txt](https://github.com/Prophet731/BFAdminCP/files/347486/laravel-2016-07-05.txt)

**Comment by killengage** [comment]
What do you want me to try, i think you forgot something ? :)

**Comment by Prophet731** [comment]
The git pull.

**Comment by killengage** [comment]
Confirmed working ! I set the ban time to 5 min. but stated (see screenshot) to 10 years, im sure this is a cosmetic issue. I check again after a couple of minutes. Thx Prophet.
![screenshot 2016-07-05 12 15 37](https://cloud.githubusercontent.com/assets/19599917/16581531/40ddecde-42aa-11e6-8bb8-e552682600ef.png)

**Comment by killengage** [comment]
hmmm...see the date its 10 years.
![screenshot 2016-07-05 12 20 11](https://cloud.githubusercontent.com/assets/19599917/16581632/e1b583ce-42aa-11e6-8b65-fcc6f2e6e70f.png)

**Comment by Prophet731** [comment]
No, that's a bug actually. I'll have to look into fixing that.

**Comment by killengage** [comment]
Something broke the "latest reports (2 weeks) ?

**Comment by Prophet731** [comment]
No?

**Comment by killengage** [comment]
Dont see the latest reports getting populated anymore. I did a git pull from you latest change (top 10 countries), but it broke the dashboard so i rolled back. Whats the best way you like me to report bugs and errors ? Git ?

**Comment by Prophet731** [comment]
You needed to clear the cache for the updated top 10 countries. That would have solved that problem.

Run this query on your database, does anything return?

```SQL
SELECT t2.*,
       t1.record_message
FROM   adkats_records_main t1
       JOIN (SELECT target_id,
                    target_name,
                    Count(record_id) AS `Total`,
                    Max(record_time) AS `Recent`
             FROM   adkats_records_main
             WHERE  command_type IN ( 18, 20 )
                AND record_time >= Date_sub(UTC_TIMESTAMP(), INTERVAL 2 week)
             GROUP  BY target_id
             HAVING `total` >= 5
             ORDER  BY recent DESC) t2
         ON t1.target_id = t2.target_id
            AND t1.record_time = t2.recent
```

**Comment by killengage** [comment]
![capture](https://cloud.githubusercontent.com/assets/19599917/16702586/55d38210-4567-11e6-9f87-8c8f7626a6cd.JPG)

**Comment by Prophet731** [comment]
If that's all the reports are returns from that SQL then that's correct. It only triggers when a player has been reported 5 or more times in the span of 2 weeks.

**Comment by killengage** [comment]
For some reason i can't clear the cache, permissions problem ? Although dir owners looking good and permissions looking good.

**Comment by killengage** [comment]
Ah ok, that makes sense ! Sorry

**Comment by Prophet731** [comment]
You need to run `php artisan cache:clear`

**Comment by killengage** [comment]
[BFACP\Exceptions\MetabansException]
  Metabans integration is not enabled.

Can i ignore this ?

**Comment by Prophet731** [comment]
Where is that coming from?

**Comment by killengage** [comment]
from the ssh session after down the artisan command

**Comment by killengage** [comment]
are you in the adkgames chatbox ? i dont want to spam your Git

**Comment by Prophet731** [comment]
Don't know why you're getting that. Just tested it and it doesn't give me that error.

**Comment by killengage** [comment]
hmmm.... (im in your chatbox btw)

**Comment by killengage** [comment]
gonna check some things

**Comment by killengage** [comment]
Only thing i see is that our hosting provider changed a portnumber of a server, i use to replace the "old" server with the new ip:port in the tbl_server table. Did that but i can't delete the obsolete server anymore, something with adkats table. You think this is causing the problem ?

**Comment by killengage** [comment]
When i enable metabans, ssh session saying this:  [BFACP\Exceptions\MetabansException]
  Metabans settings are not configured. Please update the configuration in the site settings.

When disabling metabans, this: [BFACP\Exceptions\MetabansException]
  Metabans integration is not enabled.
