### ISSUE TITLE
Pusher: You have to refresh page to see chats

### ISSUE THREAD

**Issue by killengage** [Prophet731/BFAdminCP#222]
Nice one, pusher working since last git pull. I only have to refresh the browser to see the chats. This happens on Safari and Chrome.

**Comment by Prophet731** [comment]
I'm aware of the issue, when using different clusters in pusher the chat doesn't work. I'm still trying to figure out why the cluster isn't sending the message. I'll be working on it later today (its 4am here) after work.

**Comment by killengage** [comment]
No worries, take it easy.

**Comment by Prophet731** [comment]
Problem should be solved now.

Please see this commit 37c1c66ba09b6ca79f73dea6e384ef0adeb9da80 for the additions you will need to make in your `.env` file. Your .env should somewhat reflect the example one. https://github.com/Prophet731/BFAdminCP/blob/dev-laravel5/.env.example

**Comment by killengage** [comment]
Confirmed working.

**Comment by killengage** [comment]
Is there a way the chat window opens or a popup appears when someone is chatting ? Right now the chat window closes when switching views.

**Comment by Prophet731** [comment]
That's still a work in progress and I think I would improve it in v2.2.0 https://github.com/Prophet731/BFAdminCP/issues/223 when I make the UX change.
