### ISSUE TITLE
Site Management: Servers. Trying to get property of non-object (index.blade.php)

### ISSUE THREAD

**Issue by jaggedsoft** [Prophet731/BFAdminCP#225]
After I disabled two of my servers in BFAdminCP under Site Management:Servers, I started getting this error:
Trying to get property of non-object /BFAdminCP/app/views/admin/site/servers/index.blade.php

What I would like to do is get in to Site Management: Servers, so that I can reactivate them and get the live scoreboard once more. Any ideas?

**Comment by Prophet731** [comment]
```SQL
SELECT * FROM tbl_servers WHERE GameID = 0
```

Run that query and tell me if any servers return. If they do then the problem is that one of your servers game id is no longer valid and you will need to correct that. You can find the game id in the table `tbl_games`

**Comment by jaggedsoft** [comment]
One came back, so I ran this:
`update tbl_server set GameID=1 where GameID=0;`

Now I'm getting this error when I go to Site Management: Servers:
Undefined offset: 1 (View: servers/index.blade.php)

Thanks for the help

**Comment by jaggedsoft** [comment]
![error](https://cloud.githubusercontent.com/assets/4283360/17452103/0c1ab600-5b21-11e6-90d7-ee82a9cdf77f.PNG)
![database](https://cloud.githubusercontent.com/assets/4283360/17452102/0c189d52-5b21-11e6-8e09-39ae4ee3f305.PNG)

**Comment by Prophet731** [comment]
Add your IP to the whitelist in the `.env.php` or in the `.env` file then refresh that page, it should show you more detailed debug information, you can also check the logs in the `app/storage/logs` or in `storage/logs` folder.

**Comment by jaggedsoft** [comment]
Thanks for your help! I think it was from me having a blank entry in my tbl_server. Null IP address, etc. Not sure how it got there.
When I deleted the blank row in tbl_server, it went away. If you're interested I made a modification to getPortAttribute() that defaults to port 47200 and doesn't throw an error (Invalid offset: 1) if the port is omitted from $this->IP_Address.
`    /**
     * Gets the RCON port from the IP Address
     *
     * @return integer
     */
    public function getPortAttribute()
    {
        $port = 47200; // default port
        $parts = explode(':', $this->IP_Address);
        if ( isset($parts[1]) ) $port = $parts[1];
        return (int)$port;
    }
`
![error2](https://cloud.githubusercontent.com/assets/4283360/17458526/6c2fa5f8-5bc8-11e6-8f05-77b7261c046f.PNG)

**Comment by Prophet731** [comment]
If the IP is blank then you have a bigger problem. I'm always expecting an IP or Hostname in that getPort function because it should always be there. However, i'll just modify the query to only show servers that have an IP or Hostname in the the database in the 2.1 version.

**Comment by jaggedsoft** [comment]
Thanks for making this awesome software!
