### ISSUE TITLE
Request! RSS ban feeds?

### ISSUE THREAD

**Issue by sitekeeper** [Prophet731/BFAdminCP#226]
Did you ever get the RSS ban feeds back in? I am using 2.1 bfplayforfun.org and it looks good but I am also using v2.0.0-rc.1 just for the ban feeds which work here http://www.p4fun.org/bans and it links to player info in the old RC version if you click on a ban.

Thanks
Bob

**Comment by Prophet731** [comment]
no not yet

**Comment by Prophet731** [comment]
Oh, wait I did, just forgot. I need to fix it first because it's no longer working.

Do a `git pull` on v2.1 then run `composer install`. You should then be able to access the RSS feed from this URI `//your.domain/api/bans/latest?type=rss``

**Comment by sitekeeper** [comment]
I tried just uploading the changed files and now get this error @/api/bans/latest?type=rss:
{"message":"Use of undefined constant sourceId - assumed 'sourceId' (View: \/usr\/www\/p4funtagserver\/public\/resources\/views\/system\/rss\/ban_entry_content.blade.php)","status_code":500} 

I installed it by the directions a on the 17th by using Installing Dev Version instructions  
I get this error  running git pull
fatal: Not a git repository (or any of the parent directories): .git

Thanks
Bob

**Comment by Prophet731** [comment]
Umm if you installed with those dev directions then git should have been setup. Can you tell me what commands you did (in order).

**Comment by sitekeeper** [comment]
Sorry that was my fault, I got the RSS working and clicking on a banned user's link now popup in a window. http://www.p4fun.org/bans
One more question, I still have old  v2.0.0-rc.1 running so I can now delete it and it is all the bfadmincp_ tables is that correct?

Thanks Again!!
Bob

**Comment by Prophet731** [comment]
Yes, you should be fine with deleting those tables. Only tables that start with `bfacp_` are needed. As for showing all bans no, it's just pulling the latest info. Showing all the pages is quite a lot of data without paginating it. We have ~23,000 active bans as of right now.

**Comment by sitekeeper** [comment]
OK Thanks again mine can be paginated in any size I want was the only reason I asked, but this is great how it is. 

Thanks Again!!

Bob
