### ISSUE TITLE
V2.1 changing temp voteban to Perm ban (Metabans.php) error.

### ISSUE THREAD

**Issue by sitekeeper** [Prophet731/BFAdminCP#227]
Metabans has never been on..

Editing bans seem ok but while trying to edit a vote banned player (4 hours) to Perm ban I get a page saying:
====================================
Whoops, looks like something went wrong.

1/1
FatalErrorException in Metabans.php line 261:
Call to a member function post() on null
in Metabans.php line 261
====================================
From log:
[21-Jul-2016 22:12:17 UTC] PHP Fatal error:  Call to a member function post() on null in /home/bfplayfo/public_html/bfplayforfun.com/app/Libraries/Metabans.php on line 261

The current ban I am trying to make does not show up in BFAdminCP, but everytime I try this it shows up as another (Previous ban)
From adkats_records_main:

`27065, 5, 36, 36, 1355, 'Lord-OMa11y', 29600, 'BanEnforcer', NULL, 'Banned by player Vote Ban - Lord-OMa11y (Reason: code stealer)', '2016-07-22 00:24:13', 'Y', 0),
(27066, 2, 36, 36, 1355, 'Lord-OMa11y', 29600, 'BanEnforcer', NULL, 'Banned by player Vote Ban - Lord-OMa11y (Reason: code stealer)', '2016-07-22 00:25:10', 'Y', 0),
(27067, 2, 7, 7, 239, 'Lord-OMa11y', 29600, 'P4F Ban Enforcer', NULL, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 00:50:18', 'Y', 0),
(27071, 2, 36, 36, 1355, 'Lord-OMa11y', 29600, 'BanEnforcer', NULL, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 04:21:05', 'Y', 0),
(27072, 5, 36, 36, 1355, 'Lord-OMa11y', 29600, 'BanEnforcer', NULL, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 04:45:38', 'Y', 0),
(27078, 2, 7, 7, 132480, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 07:22:55', 'Y', 1),
(27079, 2, 8, 8, 10519200, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 07:23:32', 'Y', 1),
(27081, 2, 7, 7, 132480, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 07:30:36', 'Y', 1),
(27082, 2, 8, 8, 10519200, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 07:32:55', 'Y', 1),
(27083, 2, 8, 8, 10519200, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, '(Reason: code stealer)', '2016-07-22 07:37:03', 'Y', 1),
(27084, 2, 8, 8, 10519200, 'Lord-OMa11y', 29600, 'Rand0mDeaths', 17, 'Banned by player Vote Ban - Necromantion (Reason: code stealer)', '2016-07-22 07:56:33', 'Y', 1);
`

Thanks
Bob

**Comment by Prophet731** [comment]
Do a `git pull` and see if that fixes the problem.

**Comment by sitekeeper** [comment]
Yes, that has fixed it!!!

Thanks
Bob
