### ISSUE TITLE
BFACP + Docker

### ISSUE THREAD

**Issue by jeremejevs** [Prophet731/BFAdminCP#228]
I've dockerized BFACP:

https://github.com/jeremejevs/bfacp
https://hub.docker.com/r/jeremejevs/bfacp

Just putting it out there :)

**Comment by jeremejevs** [comment]
On a related note, there's a minor issue. I get `Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE'` on `http://example.com/admin/site/system/logs`. Not sure what the cause is, don't have time to investigate, unfortunately. Probably some folder missing somewhere. Or maybe a PHP extension? I don't know. Please, look into this sometime.

**Comment by Prophet731** [comment]
Cool. I'll look into it sometime. I never really used docker.

> On a related note, there's a minor issue. I get Use of undefined constant GLOB_BRACE - assumed 'GLOB_BRACE' on http://example.com/admin/site/system/logs. Please, look into this sometime.

That's still under development for the system logs (v.2.1 at least). I haven't really worked on them in a while. The `dev-laravel5` branch will be the next release, still need to finish things that's been on my todo list for a while. Work has been keeping me from working on it usually.

**Comment by jeremejevs** [comment]
Alright, I see, thanks!
