### ISSUE TITLE
Live Scoreboard Problem

### ISSUE THREAD

**Issue by MrSpins** [Prophet731/BFAdminCP#229]
hi. ive been trying to get the Live Scoreboard working for ages now. 

i got the ports opened and working but now i seem to get a error that says "MAC is invalid."
i then goto the system logs and here is this 
production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /home4/dan/public_html/BF_Admin_Stats/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144

any help in fixing this would be nice

**Comment by sitekeeper** [comment]
re-enter your Rcon password...

Try that!

**Comment by MrSpins** [comment]
that seemed to of worked abit but for some reason now its stuck on loading the main part. http://prnt.sc/bx8tmh

**Comment by sitekeeper** [comment]
Not sure could be firewall issue, did you enter the Battlelog GUID for the server?

**Comment by MrSpins** [comment]
the page did it auto for me. but i did check to see if it was right and it is

**Comment by Prophet731** [comment]
Sorry for the late reply, didn't even see this. Where you able to resolve it?
