### ISSUE TITLE
Memberlist display

### ISSUE THREAD

**Issue by durangod** [Prophet731/BFAdminCP#23]
on the /memberlist   display i was wondering it you could adjust the array output to do 3 per row instead of 1 per row. Unless you have plans for all that space on the right?   

Im not sure im familiar  enough with this setup yet but i could give it a shot if its ok with you and send you what i did, i dont mind helping.  But when it comes to githup pulls and submits i have no idea so i can just send you what i did. I did try to learn github at one time and im so oldschool i was like forget this lol...

**Comment by Prophet731** [comment]
I've decided not to include to public memberlist
