### ISSUE TITLE
Using only V2.1 but tables bfadmincp_  being recreated

### ISSUE THREAD

**Issue by sitekeeper** [Prophet731/BFAdminCP#232]
Hi,

I am only using only V2.1, but tables from the older version are being recreated somehow, I have deleted  the bfadmincp_  tables 3 times now. Where could these be coming from?

Thanks
Bob

**Comment by Prophet731** [comment]
Is the old version running somewhere by any chance? The new version doesn't create those tables so it has to be an old install still running somewhere.

**Comment by sitekeeper** [comment]
Thanks, I did forget about one I tested with a different color scheme.

Thanks
Bob
