### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by antitoxis** [Prophet731/BFAdminCP#233]
Hello,
i have make a new site. But i get an error:
"Whoops, looks like something went wrong."
I try other webstorages. But the same.
How can i find more about this error and solve it?

Thanks.

You can check on this site.

http://server.pbstats.de/
[http://puu.sh/qvhDh/ed845cd6ea.png](http://puu.sh/qvhDh/ed845cd6ea.png)

And Tanks alot, it is a very nice project!

**Comment by Prophet731** [comment]
It's saying that the connection to your database could not be completed and was refused. This is probally a config error on your part with the database connection settings. Make sure it's all correct for MySQL login info and that the database server or web server firewall allows MySQL connections.

**Comment by antitoxis** [comment]
Hey, thanks for your Feedback.
But it was the same as in procon.

**Comment by Prophet731** [comment]
Sorry about the late reply, been very busy. Were you able to resolve this or do you still need help?

**Comment by antitoxis** [comment]
Yesthis would be great :)
I have try an other database but get the same error.

**Comment by Prophet731** [comment]
You need to make sure the user has access to the database and that the server your connecting to allows remote connections.

**Comment by antitoxis** [comment]
User is the same as the procon database. I have try it with a windows root server and a normal Hosters Database.

**Comment by Prophet731** [comment]
I do not speak German. Does your web server firewall allow port 3306 to connect to your database?

**Comment by antitoxis** [comment]
Yes, because the proconlayer connect from an other server.

**Comment by Prophet731** [comment]
You also updated the hostname in the .env file to your database address correct? If all that information is correct and you are still unable to have it connect then something else with the server is blocking it. Double check your firewalls and make sure that your web server and database server can talk to each other.

**Comment by killengage** [comment]
On your BFACP server can you do a telnet to the DB server in port 3306 ? If not, it's network related (firewall)

**Comment by antitoxis** [comment]
hey, i have change now something, and i have now a connection. But i have a other Problem.
http://stats.pb-clan.de/
If i click on Paylerstats or log, the site is not loading.
What is here the problem?

**Comment by Prophet731** [comment]
It looks like you're running a windows web server IIS? If you are then change the document root to point to the main root folder instead of the public one. I have a `web.config` file in that folder designed for that. I don't run my servers on windows IIS so I have limited experience in that.

**Comment by antitoxis** [comment]
Hey, thanks for you feedback. Now it is running :)
Yes i use windows, with plesk. I try it with a different of other Systems, but nothing work with that.
Now i have in some locations errors like this:
http://puu.sh/qYPqr/ed34dfe819.png

**Comment by Prophet731** [comment]
Follow that, http://superuser.com/a/442797

**Comment by antitoxis** [comment]
So nice it works :) Thank you so much +1:
