### ISSUE TITLE
MapNameNotFoundError on Air Superiority

### ISSUE THREAD

**Issue by RandyXp** [Prophet731/BFAdminCP#234]
Hello,
I'm running a Guilin Peaks Air Superiority only server.
The mapname (for exmaple at the live scoreboard page) is displayed as "MapNameNotFoundError" but it should obviously be "Guilin Peaks".
It would be nice if you could fix this little snippet ;)

Greets

**Comment by Prophet731** [comment]
Yeah, no problem. Would you be able to tell me what maps Air Superiority support?

**Comment by RandyXp** [comment]
Silk Road, Altai Range, Guilin Peaks, Dragon Pass and Dragon Valley 2015

**Comment by RandyXp** [comment]
Also the default tickets (vars.gameModeCounter 100) for Air Superiority are 200, not 300 as listed at the procon forum. I don't know why they got that wrong value in their lists.

**Comment by Prophet731** [comment]
I've updated the file with the new maps.

93677bc0c20ee329a22a2b5e389a568665b1be18

You just need to add those entries to the bottom of that file or just download and reupload that file.
