### ISSUE TITLE
Error when installing V2.1 

### ISSUE THREAD

**Issue by windorose** [Prophet731/BFAdminCP#235]
Hi Prophet 
When i try to install the dev version (2.1) 
i followed all step but when i enter one of this cmd : 
php artisan migrate --force
php artisan db:seed --force
and php artisan bfacp:reseed
 i have an error   [Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException]
(i have a v2.0.2 running on the same DB)

PHP 5.6.22 (cli)
5.5.51-MariaDB

**Comment by windorose** [comment]
i tried to install on other DB without bfacp table and when i run php artisan migrate --force i have this error
[BFACP\Exceptions\MetabansException]
  Metabans integration is not enabled.

**Comment by Prophet731** [comment]
You shouldn't be getting that on a fresh install of the dev copy. None of those commands should be hitting an HTTP exception. You did follow these instructions here in order correct? https://github.com/Prophet731/BFAdminCP/tree/dev-laravel5#installing-dev-version

**Comment by windorose** [comment]
yes i followed all steps in order.

**Comment by windorose** [comment]
i created a new DB and linked with XpKillers Chat and adkats , and i followed all steps and i sstill get the metaban error 
[BFACP\Exceptions\MetabansException]
Metabans integration is not enabled.

**Comment by Prophet731** [comment]
Do a `git pull` then try the setup again. I think I found where the logic error was happening.

**Comment by windorose** [comment]
Still get metaban error.

**Comment by Prophet731** [comment]
Can you delete the logs under storage/logs folder then run the commands again and after words, post that log file here as an attachment. Don't copy/paste the contents.

**Comment by windorose** [comment]
[laravel-2016-08-17.txt](https://github.com/Prophet731/BFAdminCP/files/421807/laravel-2016-08-17.txt)

**Comment by Prophet731** [comment]
So, from that log file it's saying that table `bfacp_options` doesn't exist which is a required table. I would delete all the tables that start with the prefix `bfacp_` You also need to make sure AdKats and XPKillers stats logger table exist first before you install the bfacp.

**Comment by windorose** [comment]
AdKats and XPKillers stats logger table exist 
i deleted all the bfacp_ tbl

**Comment by Prophet731** [comment]
Ok then run the migrate command only. What happens after you run that, both in the console and in the database?

**Comment by windorose** [comment]
i mad a fresh install with a DB backup (with bfacp_ tbl in) and i used only php artisan migrate --force
[laravel-2016-08-17.txt](https://github.com/Prophet731/BFAdminCP/files/421819/laravel-2016-08-17.txt)

**Comment by Prophet731** [comment]
Ok now run the db:seed command

**Comment by windorose** [comment]
the same error but no change on logs

**Comment by windorose** [comment]
[laravel-2016-08-17 (2).txt](https://github.com/Prophet731/BFAdminCP/files/421826/laravel-2016-08-17.2.txt)

**Comment by Prophet731** [comment]
Are you able to join our teamspeak? So I can see why it's not working for you. It shouldn't be difficult to install.

**Comment by windorose** [comment]
teamview?

**Comment by windorose** [comment]
or give you ssh access on PM?

**Comment by Prophet731** [comment]
teamviewer will be fine.

**Comment by windorose** [comment]
ID : 
885 886 029

**Comment by windorose** [comment]
39k5kw

**Comment by Prophet731** [comment]
I'll need the temp pass as well. I'll delete the post once connected.
