### ISSUE TITLE
Fatal Error 500 - Creating a ban 

### ISSUE THREAD

**Issue by CheckaWiemi** [Prophet731/BFAdminCP#239]
If I'm going onto a players statspage and then on "Actual bans" and then "Create ban" the following messages appears:

A fatal error occured and application could not continue. Please report this incident to the site administrator and give them the following error message.
Trying to get property of non-object (View: /usr/www/users/***bwa/BFAdminBF3/app/views/admin/adkats/bans/create.blade.php)

Everthing is working fine except this.
We're using AdKats at latest version and the AdminCP with 2.0.1

**Comment by CheckaWiemi** [comment]
Or is it maybe fixed in the latest AdminCP version?

**Comment by Prophet731** [comment]
What returns from your database when you run this query?

```SQL
SELECT * FROM tbl_playerdata WHERE GameID = 0
```

**Comment by CheckaWiemi** [comment]
"MySQL lieferte ein leeres Resultat zurück (d.h. null Datensätze). (Die Abfrage dauerte 0.0005 Sekunden.)"
MySQL returned an empty result set ( zero records )

**Comment by Prophet731** [comment]
You did set your soldiers under your account settings correct? I think the latest version (2.0.3) somewhat fixes this problem but i'm not sure if I did or not.

**Comment by CheckaWiemi** [comment]
Yeah, all soldiers are set correctly. I have also the problem (and most of our members - I guess all) that we can't perma- or tempban players via livescoreboard.

**Comment by Prophet731** [comment]
The logic for it wasn't added, one of the things I forgot when I published it. In the .env.php file add your IP address to the whitelist then try creating a ban, you should get more detailed information, if you can take a screenshot of the code that it will display on the right side.

**Comment by Prophet731** [comment]
No you add it up in the array at the top.

https://github.com/Prophet731/BFAdminCP/blob/master/.env.php#L9

**Comment by Prophet731** [comment]
Has this been resolved?
