### ISSUE TITLE
(v 2.0.2) report actions not updating, empty error

### ISSUE THREAD

**Issue by floold** [Prophet731/BFAdminCP#243]
Hey,
First of all i would like to thank you for your work, i've been using your acp for quite a while and overall it has been working very well. On v2.0.1 that was. 
(extra info)
We have/had the acp running on an external domain for quite some time (v 2.0.1) but we want to move everything to self hosting, including the acp.
Procon layers, mysql db & the web applications are all running on the same machine. 
(IIS 8 for the webpages, acp version running on own machine is 2.0.2)
Speed and reliability of the acp is way better since its running on the dedicated machine, but there are 2 problems with it, the reports & the chatlogs. (will create seperate thread for the chat problem to avoid making a mess out of this place)

The report actions aren't updating at all (the reports itself are, but you can't set actions)
It doesn't matter what action is selected, an empty error box will come up. You can see what i mean with the example report below.
![acp](https://cloud.githubusercontent.com/assets/18087749/18417513/a770f08c-7832-11e6-8ae6-29933d89e398.png)

Suprisingly enough, when making a direct copy from v2.0.1 from the externally hosted domain it will do the exact same, no error, but no result either. (indicating that it's machine related and not version)
There are no errors shown and also iis8 error log is completely empty.
The only "error" can be seen when trying to complete an action with developer tools open... "error" shown is as following:

> angular.js:9814 PUT https://trmcontrol.xyz/api/reports 405 (Method Not Allowed)
> (anonymous function) @ angular.js:9814
> m @ angular.js:9615
> f @ angular.js:9331
> (anonymous function) @ angular.js:13171
> $eval @ angular.js:14384
> $digest @ angular.js:14200
> $apply @ angular.js:14489
> (anonymous function) @ angular.js:21394
> dispatch @ jquery.min.js:3
> r.handle @ jquery.min.js:3

Any ideas where this is going wrong? All files/folders have full accessability (read/write/execute).

Kind regards,
Floold

**Comment by floold** [comment]
*update*

I just noticed that unbanning players isn't possible either. Banning however is...
It somewhat seems like there's something going wrong when the acp is trying to do an Update or Insert into the mysql db. Eventhough the account that's used has full privileges.
(in case it's necesssary... mysql: 5.6.32)

**Comment by Prophet731** [comment]
Are you running Apache or Nginx? Someone else had this problem and it was cause of the web server they used. I think it was lighttpd.

**Comment by floold** [comment]
i use IIS 8.5 on windows server 2012 :/

**Comment by Prophet731** [comment]
See http://stackoverflow.com/a/33835294

**Comment by floold** [comment]
Added pretty much every possible verb into both the applicationhost.config file and the web.config file. Both files now have the following lines added:
`<add name="ExtensionlessUrl-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />`

`<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*." verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />`

Also changed Handlers accessPolicy to `<handlers accessPolicy="Read, Write, Execute, Script">`
Just to be sure that all files have full accessability.

Unfortunately though, that didn't change it. 
(the errors only changed from 405 not allowed to 404 not found)


Went on with snooping around in the applicationhost.config file and the web.config file however.
Noticed something odd there... The default PHP handler is:
`<add name="PHP_via_FastCGI1" path="*.php" verb="GET,HEAD,POST,DEBUG" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v5.6\php-cgi.exe" resourceType="Either" />`

while it **should** be like:

`<add name="PHP_via_FastCGI1" path="*.php" verb="GET,HEAD,POST,DEBUG,PUT,DELETE,PATCH,OPTIONS" modules="FastCgiModule" scriptProcessor="C:\Program Files (x86)\iis express\PHP\v5.6\php-cgi.exe" resourceType="Either" />`

Changed the PHPhandler and added the extra verbs.
Problem solved.
Report actions & unbanning/banning are both working again as intended.

Thanks for the help though, wouldn't have found it without :)
