### ISSUE TITLE
Could not establish connection issue!

### ISSUE THREAD

**Issue by wizard45** [Prophet731/BFAdminCP#244]
Hello,

I have used this system for some time now and I am using version  v2.0.0-rc.1.  I have three servers connected to it and two work perfectly.  The third server has never worked. It keeps stating that it, "Could not establish a connection to my game server".  However it does show the chat logs.

Its been a while since I set this up, but can you confirm that in the edit game server page, the "Rcon Password" box is my procon password that I use to connect to my Layer server?  If not, what password do I look for. 

Also, if you not sure what is causing this, can you tell me where I can find an error log file somewhere that maybe is showing what the issue is.

I have check all possible firewall IP address with the webpage and I cannot find any reason for this not to connect.  I have look for an error log folder but cannot find one.

Any ideas or help would be appreciated!

Thank you

**Comment by Prophet731** [comment]
1) Make sure the rcon port to your gameserver is open on the firewall on your web server for the outgoing connection.

2) The RCON password is the one you set on the gameserver, not the procon accounts. Use the same password that the parent layer uses to connect to the game server.

**Comment by wizard45** [comment]
> 2) The RCON password is the one you set on the gameserver, not the procon accounts. Use the same password that the parent layer uses to connect to the game server.

Sorry for my questions, but I'm not quite sure what you mean here.  For example, my game server provider is GameServers.  Do I use the password that I have to log onto my GameServers account?

Also, is there an error log folder somewhere where I can see if there are some errors reporting IP address that are not being able to connect.  I have entered about every IP address that I can find for this server in the firewall.

Thank you for your time and help.

**Comment by killengage** [comment]
Procon and RCON are 2 different things. Normally you will get a special RCON password for each server. Its only a password there is no username.

From the Gameserver forum:

You can find your rcon password in your server.cfg file /cfg folder.

Or login to http://my.gameservers.com/ control panel and click on the INFO button of your tf2 game server and click on the config tab and you'll see the rcon password there also.

Sounds like you are still using the default rcon password that was given to you by gameservers you might want to change it once you are there.

**Comment by wizard45** [comment]
Well it looks like I am using the correct password and I have listed every IP address link to this server.  I have listed every IP address that I can find that is linked to my database firewall.  I guess I need to contact gameservers to see if they have a firewall issue on their side that is blocking it.

Again, thank you for your help.

**Comment by killengage** [comment]
The reason chatlogs work is because it is using procon (statslogger plugin and ADKATS). The RCON is for the "live scoreboard".

**Comment by windorose** [comment]
@wizard45 
you can find your RCON password on gameservers.com
click on you server and go to config tab (Admin Password)
![github h](https://cloud.githubusercontent.com/assets/18490426/18958539/ea1d45f0-8630-11e6-9d28-697b5bfd5d6c.png)

**Comment by wizard45** [comment]
Thank you windorse!

I am using the correct password, but I think my issue is with Gameserver.  I think they have firewall that is blocking me.

**Comment by Prophet731** [comment]
Has this been resolved?

**Comment by wizard45** [comment]
Hello,

I was never able to fix this issue.  I contacted Game Servers to see if they had a firewall that was blocking and they reported that they were not.  They open up everything to all IP's and it would not connect.  I have three servers and two of the servers have the same port number, but the third server had a different port number.  The servers that were working with BFadminCp were the servers with the same port number.  Game Servers felt that the cause of my problem was that the third server had a different port number was the reason why BFadminCP is not working on the third server.  

After nearly spending about 10 hours on this trying to fix it, I had to finally give up and not use it on our third server.  

I truly enjoy your work and want to thank you for your efforts.

Thanks,

Wiz

**Comment by Prophet731** [comment]
The only thing I could think of is a different RCON port than the one it's seeing.

**Comment by wizard45** [comment]
Game Servers confirmed my port number as correct and I don't know what else to do.  This issue has stumped me for several months and for the life of me I can't figure it out.

**Comment by wizard45** [comment]
I am going to close this post because that server is going to be shut down in a couple of weeks.  

Thank you for trying to help me, I do appreciate everything you tried to do for me.
