### ISSUE TITLE
Fragify - Free servers for everyone

### ISSUE THREAD

**Issue by mambochambo** [Prophet731/BFAdminCP#247]
hey Prophet, i know this is off topic,
but its the only way i can reach you.

its me MAMBOJUMBO. You helped me with BFAdmin, if you remember.
We have successfully achieved a Project, hosting Battlefield Server in GCC-Countries. We are in close contact with a Gaming Provider.
Since you are a Developer in Adk. The Manager of that company asked me if i have interesst in his Project he once initiated:

https://www.reddit.com/r/GlobalOffensive/comments/48iwqt/fragify_free_servers_for_everyone/?st=iucnzowq&sh=c600882d

I have no clue about Programming, but i was thinking of you, so....
They are working also for ESL and did their backend. I can introduce you to him, in case you have intresst in working on a Project like this.

Kind Regards

Christoph Weidemann

**Comment by Prophet731** [comment]
Unfortunately, I no longer have the time for a project like that. I can barely even get a chance to work on the BFACP right now.
