### ISSUE TITLE
Playerlist in Livescoreboard BF3

### ISSUE THREAD

**Issue by CheckaWiemi** [Prophet731/BFAdminCP#248]
Hi,

I got a huge problem since a few days.
Therre are no playerlist in my livescoreboard anymore: https://abload.de/img/livescoreboardrwukg.png

I tried nearly everything to fix it but nothing worked.
The problem is just in BF3. Bf4 and BFH is working very well.
Some friends of mine using also BFAdminCP got exactly the same issue since about 4 or 5 days. Before it worked always great and there were no problems. Maybe someone can help me please :-/

**Comment by Prophet731** [comment]
Most likely a BF3 update happened and it broke the way the RCON reads the data in the app. I'll need to find a fix for it.

**Comment by CheckaWiemi** [comment]
Meanwhile there is no scoreboard available anymore :-(

**Comment by Prophet731** [comment]
This has been fixed. Apparently they added a value to the response that comes back for the player list and it messed up the key I use to get the total players. It's a simple fix which if you're running version 2.1 you can easily update it.

Go to the following file and change this value to the one in green.

https://github.com/Prophet731/BFAdminCP/commit/c58d8fc324d885b0ef4c17ba5f53d9a34fb02c6d

**Comment by CheckaWiemi** [comment]
To be honest: I LOVE YOU :-*  ;-)

I use version 2.0.1 and the file is another folder, but I found it and changed it.

I thank you very very much! You did a great job! Thanks :-)

**Comment by IamDontNoob** [comment]
Hello.
We use and like v2.0.0-rc.1 version of BFADMINCP.
But on this version i not found $nRows = $res[9]; in BF3Conn.php

Can you help with this?
Thank you.

**Comment by CheckaWiemi** [comment]
Is it possible to upload your BF3Conn.php anywhere and post the link to it here?

**Comment by IamDontNoob** [comment]
Hey CheckaWiemi.
Thank you for you fast answer, here link https://www.dropbox.com/s/tcxmkt90xh1mfjc/BF3Conn.php?dl=0

**Comment by CheckaWiemi** [comment]
Mmhhhh sorry but I can't find something that would fix it.
Maybe you should update your whole BFAdminCP to version 2.0.1 or higher?

**Comment by IamDontNoob** [comment]
:( i like this version v2.0.0-rc.1
