### ISSUE TITLE
No pop out menus

### ISSUE THREAD

**Issue by SpankDaddy** [Prophet731/BFAdminCP#249]
I have a few issues, but to start - I just installed the BFAdminCP and once installed, everything seems to be working and I am logged in as Administration, however: 

Issue 1: There are NO popout menus for 'AdKats Management' or 'Site Management'. When I mouse over it simply shows 'javascript://' and nothing else. Clicking them does nothing. 

Issue 2: When accessing the live scoreboard I see this error:

Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists. 

Anyone have any ideas?

**Comment by Prophet731** [comment]
What's the link to it? It sounds like it's not able to load some JS files.

**Comment by SpankDaddy** [comment]
http://admincp.bgcgaming.com/public

Thanks - let me know if you need access etc..

**Comment by Prophet731** [comment]
Well, I already see the problem with that url. You're suppose to have the document root set to the public folder. You're not suppose to be accessing it from /public in the browser.

**Comment by SpankDaddy** [comment]
You lost me there. I have it set to http://admincp.bgcgaming.com, but then it forwards to the pub folder. Is this not correct?

**Comment by Prophet731** [comment]
No it's not supposed to redirect to that folder. When first setting up the sub domain you should have an option to set up the document root,  this is where you need to set it to the public folder it is not a redirect.

**Comment by SpankDaddy** [comment]
So it should be a admincp.bgcgaming.com as the subdomain and admincp.bgcgaming.com/public as the root?

**Comment by Prophet731** [comment]
`admincp.bgcgaming.com` should be the main url you access. The `/public` is the folder provided by the application, so when you create the subdomain do you have the ability to have it point to a specific folder (document root)? Best example I can give you is this for an Nginx server setup.

https://github.com/Prophet731/BFAdminCP/wiki/Nginx-Rules-for-the-BFAdminCP

Notice how `root` has it set to the public directory of the application. That's what the subdomain document root (path) needs to be set too.

**Comment by SpankDaddy** [comment]
Removed everything and re-created the domain with root to public. Re-uploading now and will keep you posted. 

Cheers!

**Comment by SpankDaddy** [comment]
That definitely fixed it. Menus are working now - however now I'm seeing this error on the live scoreboard"
Could not connect to server. It may be offline or port is closed. Please try again later.
Server is running and as far as I can tell the proper information has been added.

**Comment by SpankDaddy** [comment]
I've read all the documentation on this and have looked at everything I possibly could do to get this working. 
Added the Rcon IP, Added the gameserver IP, confirmed the firewall is NOT running on the game server as they state in their firewall section. Confirmed gameserver is listed in the remote SQL.

**Comment by Prophet731** [comment]
https://github.com/Prophet731/BFAdminCP/wiki/FAQ#5-error-connection-could-not-be-established-to-game-server

Most likely your problem.

**Comment by SpankDaddy** [comment]
Sorry for the late reply. I've checked this and everything is working as required in the FAQ. There is no firewall on the server so as far as I can tell, all the ports are open. Still the error persists. I'm at a loss on this one.
