### ISSUE TITLE
Could not set encryption key

### ISSUE THREAD

**Issue by dzieju** [Prophet731/BFAdminCP#251]
Hi
I cant generate key ... help 
Could not set encryption key

Link dont work 

https://api.gamerethos.net/random_key

**Comment by Prophet731** [comment]
http://api.gamerethos.net/random_key

Try without the https.

**Comment by dzieju** [comment]
Is working . Thx .
But why i dont see more options like server settings and other ? 

![screenshot 2017-03-22 16-19-47](https://cloud.githubusercontent.com/assets/11342285/24205342/68fe19f8-0f1b-11e7-81d4-b17bda427f80.jpg)

**Comment by dzieju** [comment]
Can you answer ?

**Comment by Prophet731** [comment]
Check in the bfacp_roles tables and find your user ID entry. Change the role_id to a 1 if it's not already.

**Comment by dzieju** [comment]
Thx it was in bfacp_assigned_roles

**Comment by dzieju** [comment]
i have another problem  this bfadmincp  not wotking on php7 how i can fix this ?

**Comment by Prophet731** [comment]
It's actually not compatible with PHP 7 out of the box and I haven't messed with PHP7 to get it all to work correctly. So I do not have an answer for you on how to mod it to make it work.

**Comment by dzieju** [comment]
OK. Thx very much .
