### ISSUE TITLE
BFAdminCP Live problem

### ISSUE THREAD

**Issue by Lima-Charlie** [Prophet731/BFAdminCP#255]
Hi Prophet and the overs,

For start, thank you very much for this tool, I can use it before and it's very very good.

So I start my own server and I want to use BFAdminCP. I add AdKats on the server (procon), but I have a problem, and after two weeks, I don't found a solution ...

The live board don't work, I can't see the players online, the round, ... and when I'm on a server I can't choose an over with the toolbar. I need to go back on home and click to the over server.

You can see the panel on this adress : http://uag.mg-community.de

Thanks for your help and have a good evening.
Lima

**Comment by mpoonuru** [comment]
Your servers query ports are opened on web server? Make sure any firewalls are not blocking the ports.

**Comment by Lima-Charlie** [comment]
Hi mpoonuru,

Thanks for your fast answer. The all port are open. A friend use the panel on the same host (I use is account) and he don't have trouble. I think it's on procon or mysql but don't found ...

**Comment by mpoonuru** [comment]
I didn't get you! A friend uses panel on same host? I am sorry I didn't understand, even the live score board is not working when I access it.

Can you please explain it a bit clear,

**Comment by Lima-Charlie** [comment]
I'm sorry, I have difficulty with english ^^. A friend have an over panel for his server. But we use the same account on the host. We have just create two different space on the hard disk and two subdomain for seperate the two panel admin. So the configuration of port and firewall are the same but adminpanel works fine for him.

**Comment by mpoonuru** [comment]
Did he copy the same files to your sub domain? Have you guys checked the permissions for storage folder and builds folder?

**Comment by Lima-Charlie** [comment]
We download each over the tools on web site and copy the files but normaly it's the same files with different information for mysql. I checked the permissions for storage folder but what's builds folder ?

**Comment by Prophet731** [comment]
If you have a different RCON port than he does then you will have to open that one up as well. If you're on the same webspace and use the same RCON port then their shouldn't be a problem.

**Comment by Lima-Charlie** [comment]
We have different RCON, but for him the port are open.

**Comment by Lima-Charlie** [comment]
Problem solved, thanks for your help.
