### ISSUE TITLE
 Fatal System Error!  The given data failed to pass validation.

### ISSUE THREAD

**Issue by mpoonuru** [Prophet731/BFAdminCP#256]
Hi @Prophet731 ,

When somebody try to register on my https://admin.corehqnetwork.com, they get  Fatal System Error!

The given data failed to pass validation.

Could you please help me?

**Comment by Prophet731** [comment]
Sorry for the late reply, been busy with work. Only reason that will happen is if the email, username, or password don't pass the required validation. 

The rules required are listed below.

Username needs to be unique, minimum of 4 characters, and contain only letters, numbers, hyphen, or underscore.

Email needs to be unique as well and be valid.

Password needs to be a minimum of 8 characters.

```PHP
    public static $rules = [
        'username' => 'required|unique:bfacp_users,username|alpha_dash|min:4',
        'email'    => 'required|unique:bfacp_users,email|email',
        'password' => 'required|min:8|confirmed',
    ];
```

**Comment by mpoonuru** [comment]
Hi Bro,

Thank you so much for your response! I have just tested this after your response! You are right! Is there a way to add a validation instead of this error?

**Comment by Prophet731** [comment]
Well that is the error, at least that's what it should display.

**Comment by mpoonuru** [comment]
Haha, that's true bro. If I get a chance, I will try to write my code. Thanks a lot brother for your time.
