### ISSUE TITLE
default login not working

### ISSUE THREAD

**Issue by xX-TONNE-Xx** [Prophet731/BFAdminCP#257]
Hi,

I have installed BFAdminCP as described and I also come to the dashboard page, but if I want to log in, he does not accept the default password. Did I do something wrong?

**Comment by mpoonuru** [comment]
Create a new account, if you have access to the database, you need to edit the got to bfacp_user_role and change the role of to 1for your account, everything works.

**Comment by xX-TONNE-Xx** [comment]
it is working, thx.
