### ISSUE TITLE
Fatal Error on Live-Score-Board

### ISSUE THREAD

**Issue by xX-TONNE-Xx** [Prophet731/BFAdminCP#258]
The error is produced when I click on the link "Live Scoreboard"

Fatal Error! The request couldn't complete due to a server side error. Please choose another server or retry. Notify an administrator if this error persists.
socket_set_option(): unable to set socket option [99]: Option not supported by protocol.

**Comment by Prophet731** [comment]
Which game are you running this for?

**Comment by xX-TONNE-Xx** [comment]
Battlefield 4, Gameserver and DB hosted by Nitrado, Homepage hosted by Strato.

**Comment by Prophet731** [comment]
Ok in this file https://github.com/Prophet731/BFAdminCP/blob/master/app/bfacp/Libraries/BF4Conn.php#L111 comment out these two lines like so.

```PHP
// socket_set_option($this->_sock, SOL_SOCKET, SO_RCVTIMEO, ['sec' => 5, 'usec' => 0]);
// socket_set_option($this->_sock, SOL_SOCKET, SO_SNDTIMEO, ['sec' => 5, 'usec' => 0]);
```

**Comment by xX-TONNE-Xx** [comment]
thanks, ist worked now :-)
