### ISSUE TITLE
Add active web and in-game admins to dashboard

### ISSUE THREAD

**Issue by Hutchew** [Prophet731/BFAdminCP#33]
Would be awesome to know who is online and doing their job at any given moment.
Maybe squinch down the bans today/average bans/players online into one side, and stuff active webadmins/game admin on the other?
possibly even a link to their profiles right from there?

Anyway, very nice job, guys. Everybody loves the new functionality and look.

**Comment by Prophet731** [comment]
I've added this to the dashboard but it only works for those that are in game.

**Comment by iraqiboy90** [comment]
By any chance, is this related? https://github.com/Prophet731/BFAdminCP/issues/66

**Comment by Prophet731** [comment]
@iraqiboy90 

No it's not.
