### ISSUE TITLE
REQUEST: Add page for populating players for the past week

### ISSUE THREAD

**Issue by ColColonCleaner** [Prophet731/BFAdminCP#44]
Selector:

SELECT 
	`target_name` AS `player`, 
	COUNT(`record_id`) AS `populations_pastweek` 
FROM 
	`adkats_records_main` 
WHERE 
	`command_type` = 88
AND 
	DATE_ADD(`record_time`, INTERVAL 7 DAY) > UTC_TIMESTAMP()
GROUP BY
	`target_id`
ORDER BY
	`populations_pastweek` DESC, `target_name` ASC;

**Comment by Prophet731** [comment]
Should this be something on the dashboard or on the server stats page?
