### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by tmiland** [Prophet731/BFAdminCP#52]
Hi,

do you have any API Documentation?

Is it f.eks possible to get a response if a player is in the db or not? Something like bf4stats.com api: http://api.bf4stats.com/api/playerInfo?plat=pc&name=TommyMiland&output=json&opt=id

Thanks,
Tommy.

**Comment by iraqiboy90** [comment]
Well... if you want to fix the random spam registration, the best and most efficient way is to change the filename of the registration page, and of course tell everything else (system) about the new filename.
I did it for vbulletin and there was not a single random spam registration ever since.

**Comment by Prophet731** [comment]
@tmiland 

Do you still need a way to check for an existing player?
