### ISSUE TITLE
Add support for SQDM

### ISSUE THREAD

**Issue by Flat01** [Prophet731/BFAdminCP#54]
Add support for SQDM

**Comment by Flat01** [comment]
Does Version 2.0.0 RC.2 support SQDM?

**Comment by Prophet731** [comment]
No. It will be on 2.0.0.

I was fixing some release stuff so sorry for the notifications if you got them.

**Comment by Flat01** [comment]
no worries. I have a clan full of admins itching to use this.

**Comment by Prophet731** [comment]
Added
