### ISSUE TITLE
Request: "Unregistered" role

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#60]
Hello

I remember 1.4.4 had this role available to modify.
Is it possible to bring it back to the new version? with a lot more options?
- Can see name history option
- Can see IP option
- Can see Chatlog option
- Can see Live ScoreBoard option
- Can see Server Statistics option
- Can see Memberlist option
- Can see Leaderboards option
- Managements pages should hidden anyways..

and possibly more

regards
iraqiboy90

**Comment by Prophet731** [comment]
Yeah, I can add this.

**Comment by iraqiboy90** [comment]
:+1:

**Comment by Prophet731** [comment]
Added.

**Comment by Prophet731** [comment]
Quick update.

I've decided to just make these settings that you can change in the site management. No "Guest" role will exist in v2.

**Comment by iraqiboy90** [comment]
You mean like "default permissions" and then the usergroups overrides that?

**Comment by Prophet731** [comment]
They will only affect those not logged in.
