### ISSUE TITLE
Issue? Player Graph not dropping to 0

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#61]
Hello

The player graph never drops to 0, making it kinda confusing for some of the admins.
http://imagizer.imageshack.com/img673/2355/yn1mi2.png
On this image, it should have dropped to 0 players at about 02:30

**Comment by Prophet731** [comment]
This has been fixed with 44302e1fce531aecfb3cde04b79b25f1be803b98 and f0f7d78f0c58a0a17622a692d45ec2976da165fa
