### ISSUE TITLE
REQUEST: DPS display change to percentage

### ISSUE THREAD

**Issue by ColColonCleaner** [Prophet731/BFAdminCP#68]
Currently the DPS of a weapon listed under suspicious weapons is in actual DPS. Request that it be changed to % reference to what that weapon normally deals for damage, giving it a good meaning. Not everyone has memorized the DPS values for each weapon.

AEK deals 24 DPS. Player is dealing 37 DMS with it. Column shows 154%.

**Comment by iraqiboy90** [comment]
hi
at what section is this on the panel already? I thought the statlogger doesnt collect shots/hits

**Comment by Prophet731** [comment]
@ColColonCleaner this is only for us. No one else has it. It was by AOB request for that when I asked him. I'll have to ask him again if I can make this into the public version. I'm trying to remain on good terms with him. lol

@iraqiboy90 Our version has a built-in suspicious weapons listing that isn't in the version you're using. That's the only thing different from ours vs everyone else.

![](http://i.gyazo.com/457ac7428701253a16934a19b03ab216.png)

It's pulling the players battlelog stats so i'm able to get the shots and hits from their battlelog profile.

**Comment by Prophet731** [comment]
This will be added in the public release now.

**Comment by iraqiboy90** [comment]
:+1:
