### ISSUE TITLE
Request: DPS details on sessions; Yay or Nay?

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#71]
On the players profile there are sessions details which are pulled from the statlogger plugin, but is it possible to add a DPS details on those sessions pulled from BL or bf3stats/bf4stats?

**Comment by iraqiboy90** [comment]
Or if possible a cron-job based round detail for all players including the DPS taken from BF3stats/BF4stats?

How long does something like this take?
@ColColonCleaner

**Comment by ColColonCleaner** [comment]
The information is not available, easily anyway, sorry. This requires extensive querying of battlelog, several queries deep.

**Comment by Prophet731** [comment]
That's way too much and your server would be IP banned from battlelog and quite possibly from BF3/4 Stats. It's would also be very very slow, like really slow to try and bypass this and make it work without getting banned.
