### ISSUE TITLE
Problem with Gun Master server

### ISSUE THREAD

**Issue by antivanity** [Prophet731/BFAdminCP#75]
With battlefield's new game mode GunMaster, i am getting an error of "end() expects parameter 1 to be array" while viewing the 'Live Scoreboard'.

I have updated to the latest version on Github here with no effect.

**Comment by antivanity** [comment]
Forgot to mention this is on the 'Live Scoreboard' page.

**Comment by antivanity** [comment]
Opps didn't mean to close this.

**Comment by Prophet731** [comment]
Current version doesn't support gunmaster. Version 2 will have support for it, however, it's still in development and is set to be release June 10th.

**Comment by antivanity** [comment]
Have the changes that fix this been merged into 2.0-rc2 ? I downloaded that and still having the same problem

**Comment by Prophet731** [comment]
No, it's fixed in Version 2.0.0

http://www.adkgamers.com/topic/117610-bfacp-version-200/
