### ISSUE TITLE
Live Scoreboard: colour notification when player dies

### ISSUE THREAD

**Issue by Subman-CNP** [Prophet731/BFAdminCP#84]
On the Live Scoreboard on version 2.0.0 there's now a very cool feature, that highlight a player, when a player will kill somebody. Here is some enhacement feature:
1. increase a dim delay, so that it would stay as long as it's currenlty on the procon GUI (it's optimal in my opinion)
2. colour notification when player dies (eg. blue)

**Comment by ColColonCleaner** [comment]
In procon it's blue flash on kill, red flash on death.

Something that might be cool to test is green flash on spawn, but that could be too much happening on screen. Maybe a checkbox that's off by default.

Another thing that might be cool is drawing a thin black line between the killer/victim for the duration of the blue/red animation, but once again could be too much. Maybe a checkbox that's off by default.

**Comment by Subman-CNP** [comment]
yeah, the flash on spawn should be off by default, but it could be a cool feature as well.
I don't think it would be easy to draw a line between the killer and victim, especially that there are situations, when somebody will kill 2 or more opponents at the same time, so there could be a situation when there should be several lines from one player. Also too much will be happening on the live scoreboard in my opinion.

**Comment by Prophet731** [comment]
This is not possible. It doesn't maintain a connection to receive events like that.
