### ISSUE TITLE
Player profile no name causes exception

### ISSUE THREAD

**Issue by Subman-CNP** [Prophet731/BFAdminCP#85]
Version: 2.0.0.
Link for the banned players that were imported by AdKats from procon ban list (ban not by name, but by EA GUID for example) is displayed incorectly. On the 2.0.0rc2 there was a following link for the players ban on banlist:
`<a href="http://FQDN/player/14577/NoNameTarget">NoNameTarget</a> `

On the 2.0.0 version a link is wrong:
`<a href="http://FQDN//players/14577">http://FQDN/players/14577</a>`

When I will click on players ban, then I will recevice a following HTTP error: 
`Error in exception handler.`

**Comment by Prophet731** [comment]
I don't quite understand?

**Comment by Subman-CNP** [comment]
My banlisst manager view on BFACP 2.0.0 :
http://i.imgur.com/J1AaLlX.png
When I will select player id 14579 then I will receive a following error:
http://i.imgur.com/2nhXCaG.png

The same ban list on the BFAdminCP 2.0.0rc1:
http://i.imgur.com/E2KP23D.png
When I will select player id 14579:
http://i.imgur.com/rdLmIdH.png

**Comment by Subman-CNP** [comment]
I hope it's more clear now.

**Comment by Prophet731** [comment]
Whitelist your IP address in the .env.php file at the top and revisit the player. It should show you a more detailed message. Send me a screenshot of that.

**Comment by Subman-CNP** [comment]
I've whitelisted my public IP address, however now I'm receiving "HTTP 500 Internal Server error" message instead of "Error in exception handler.". However, I know how to correct this error. I've just changed the URI from "/players/<ID>/" to "/players/<ID>/NoNameTarget" and BFACP 2.0.0 displays this ban correctly. See: http://i.imgur.com/zUNnRm1.png

**Comment by Prophet731** [comment]
Oh I see what it is. It's the breadcrumbs and it's expecting to have a value for the name.
