### ISSUE TITLE
Chatlog search -> only finds chat record if keyword is the first word

### ISSUE THREAD

**Issue by scotlanddig** [Prophet731/BFAdminCP#86]
app/bfacp/Http/Controllers/ChatlogController.php:63

$query->orWhere('logMessage', 'LIKE', sprintf('%s%%', $keyword));

The lack of a "%" before the $keyword means the results will only return a record where the keyword is the first word in the logMessage field

**Comment by Prophet731** [comment]
Good catch, i'll put this on the todo list.
