### ISSUE TITLE
Wrong timestamps on panel ban edits

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#94]
Has this been addressed?

![addressed](https://cloud.githubusercontent.com/assets/8139556/8638984/9f251e1a-28cb-11e5-92da-77c8bb5462d3.PNG)

So this player has been banned by autoadmin on the Jul 11, 2015 6:37pm CEST.
I disable the ban, even though it was already expired, and the date is Jul 11, 2015 6:37pm CEST again?

It should say Jul 12, 2015 7:15pm CEST

btw, this is not the first player this issue is on.
A mess gets created when players bans gets edited, specially when done multiple times on the same player....

**Comment by Prophet731** [comment]
This has been fixed in the 2.0.0 release.

http://www.adkgamers.com/topic/117610-bfacp-version-200/#entry404982
