### ISSUE TITLE
REQUEST : select timezone

### ISSUE THREAD

**Issue by ChaT0n** [Prophet731/BFAdminCP#95]
Adding the possibility in the settings to chose the timezone (UTC or CET) with +/- hours. LIke this the chatlogs in the database and the chat in the bfadmincp will have the same time.
Cause if we change the timeoffset in the chatlooger plugin (-2 for example) , the logdate in the chatlogs in the database will have two hours late over the real time of the message

**Comment by Prophet731** [comment]
Have AdKats post the chatlogs and set feed chat logger to on. This will deal with posting the date/times correctly.

**Comment by ChaT0n** [comment]
Problem solved and clarified over ts
